# 05_Modeling (v2)

Notebook ini menyiapkan pipeline modeling untuk LSTM univariat (contoh untuk satu komoditas). Termasuk: persiapan dataset, dataset class, model (menggunakan `src/models/base_model.py`), loop training singkat untuk validasi end-to-end, dan evaluasi metrik dasar.

## Konfigurasi dan Persiapan

Notebook menggunakan parameter dari `config.yaml`.

In [11]:
import yaml
from pathlib import Path
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, random_split
from sklearn.preprocessing import StandardScaler

# Load config
cfg = yaml.safe_load(Path('../config.yaml').read_text())
model_cfg = cfg['model']['univariate']
seq_len = model_cfg.get('sequence_length', 28)
hidden_size = model_cfg.get('hidden_size', 64)
num_layers = model_cfg.get('num_layers', 2)
dropout = model_cfg.get('dropout', 0.2)
lr = model_cfg.get('learning_rate', 1e-3)
batch_size = model_cfg.get('batch_size', 64)
epochs = 60 
use_cuda = cfg.get('training', {}).get('use_cuda', True) and torch.cuda.is_available()
device = torch.device('cuda' if use_cuda else 'cpu')
print('Device:', device)

Device: cuda

In [12]:
# Jalankan training langsung dari notebook menggunakan skrip `src/train.py`
import subprocess, sys
import yaml
from pathlib import Path
project_root = Path('..').resolve()
compare_csv = project_root / 'runs' / 'all_commodity_compare.csv'
compare_csv.parent.mkdir(parents=True, exist_ok=True)

cfg = yaml.safe_load((project_root / 'config.yaml').read_text())
batch_size = cfg['model']['univariate'].get('batch_size', 64)
epochs = 60

# Set one commodity to run here; set run_all = True to execute every commodity in config
train_commodity = 'Beras Medium'
run_all = True
commodities = [c['name'] for c in cfg['commodities']] if run_all else [train_commodity]

for series in commodities:
    print('\n=== Running commodity:', series, '===')
    cmd = [
        sys.executable,
        str(project_root / 'src' / 'train.py'),
        '--commodity', series,
        '--mode', 'both',
        '--epochs', str(epochs),
        '--batch-size', str(batch_size),
        '--device', 'cuda' if torch.cuda.is_available() else 'cpu',
        '--log-dir', str(project_root / f'runs/{series.replace(" ", "_")}'),
        '--log-csv', str(project_root / 'runs' / f'metrics_{series.replace(" ", "_")}.csv'),
        '--compare-csv', str(compare_csv),
        '--early-stopping-patience', '10',
    ]
    try:
        subprocess.run(cmd, cwd=str(project_root), check=True)
    except subprocess.CalledProcessError as e:
        print('Error running', series, e)
        continue

print('\nAll runs finished. Loading comparison CSV:')
import pandas as _pd
if compare_csv.exists():
    comp_df = _pd.read_csv(compare_csv)
    display(comp_df)
    comp_df
else:
    print('Comparison CSV not found at', compare_csv)

=== Running commodity: Beras Premium ===

2026-06-02 15:17:40.127912: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 15:17:40.168730: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 15:17:40.186477: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 15:17:40.191114: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 15:17:40.212958: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Device: cuda
Epoch 1/60 - train_loss=0.794795 val_loss=0.687540
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 2/60 - train_loss=0.180737 val_loss=0.151879
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 3/60 - train_loss=0.081327 val_loss=0.042371
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 4/60 - train_loss=0.054828 val_loss=0.037200
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 5/60 - train_loss=0.042210 val_loss=0.072270
Epoch 6/60 - train_loss=0.035821 val_loss=0.034931
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 7/60 - train_loss=0.030186 val_loss=0.037644
Epoch 8/60 - train_loss=0.024937 val_loss=0.027221
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 9/60 - train_loss=0.021620 val_loss=0.022544
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 10/60 - train_loss=0.018002 val_loss=0.019303
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 11/60 - train_loss=0.014335 val_loss=0.017885
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 12/60 - train_loss=0.011264 val_loss=0.017533
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 13/60 - train_loss=0.011259 val_loss=0.015920
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 14/60 - train_loss=0.010701 val_loss=0.016314
Epoch 15/60 - train_loss=0.008999 val_loss=0.015859
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth
Epoch 16/60 - train_loss=0.009371 val_loss=0.016019
Epoch 17/60 - train_loss=0.008401 val_loss=0.016239
Epoch 18/60 - train_loss=0.007919 val_loss=0.017786
Epoch 19/60 - train_loss=0.009622 val_loss=0.017650
Epoch 20/60 - train_loss=0.008691 val_loss=0.016494
Epoch 21/60 - train_loss=0.008870 val_loss=0.016404
Epoch 22/60 - train_loss=0.009955 val_loss=0.020374
Epoch 23/60 - train_loss=0.008913 val_loss=0.021557
Epoch 24/60 - train_loss=0.007927 val_loss=0.016705
Epoch 25/60 - train_loss=0.007527 val_loss=0.017418
Early stopping after 25 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/univariate/lstm_Beras_Premium_univariate.pth for final evaluation
Training finished in 2.2 sec

Final test metrics:
MAE: 139.256 Rp/kg
RMSE: 139.532 Rp/kg
MAPE: 1.071 %
sMAPE: 1.065 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Epoch 1/60 - train_loss=0.213375 val_loss=0.172638
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 2/60 - train_loss=0.018001 val_loss=0.169756
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 3/60 - train_loss=0.006877 val_loss=0.151288
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 4/60 - train_loss=0.005305 val_loss=0.154378
Epoch 5/60 - train_loss=0.005131 val_loss=0.154107
Epoch 6/60 - train_loss=0.004703 val_loss=0.150605
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 7/60 - train_loss=0.004461 val_loss=0.142836
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 8/60 - train_loss=0.004154 val_loss=0.138868
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 9/60 - train_loss=0.004185 val_loss=0.137072
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 10/60 - train_loss=0.003852 val_loss=0.142085
Epoch 11/60 - train_loss=0.004139 val_loss=0.141250
Epoch 12/60 - train_loss=0.003611 val_loss=0.129827
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth
Epoch 13/60 - train_loss=0.003931 val_loss=0.136429
Epoch 14/60 - train_loss=0.003696 val_loss=0.140821
Epoch 15/60 - train_loss=0.003793 val_loss=0.141468
Epoch 16/60 - train_loss=0.003625 val_loss=0.144504
Epoch 17/60 - train_loss=0.003171 val_loss=0.137159
Epoch 18/60 - train_loss=0.003334 val_loss=0.139365
Epoch 19/60 - train_loss=0.003207 val_loss=0.137025
Epoch 20/60 - train_loss=0.002878 val_loss=0.140319
Epoch 21/60 - train_loss=0.002912 val_loss=0.143007
Epoch 22/60 - train_loss=0.002856 val_loss=0.146131
Early stopping after 22 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Premium/multivariate/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.2 sec

Final test metrics:
MAE: 434.223 Rp/kg
RMSE: 434.468 Rp/kg
MAPE: 3.340 %
sMAPE: 3.285 %
Directional Accuracy: 0.00 %
Comparison output file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/all_commodity_compare.csv

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

=== Running commodity: Beras Medium ===

2026-06-02 15:17:50.097461: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 15:17:50.111614: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 15:17:50.130504: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 15:17:50.136227: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 15:17:50.149335: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Device: cuda
Epoch 1/60 - train_loss=0.724047 val_loss=0.845130
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 2/60 - train_loss=0.167575 val_loss=0.131668
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 3/60 - train_loss=0.074472 val_loss=0.033305
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 4/60 - train_loss=0.045782 val_loss=0.031318
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 5/60 - train_loss=0.034143 val_loss=0.032045
Epoch 6/60 - train_loss=0.027721 val_loss=0.031851
Epoch 7/60 - train_loss=0.023389 val_loss=0.031354
Epoch 8/60 - train_loss=0.017966 val_loss=0.028105
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 9/60 - train_loss=0.012911 val_loss=0.037669
Epoch 10/60 - train_loss=0.011131 val_loss=0.040050
Epoch 11/60 - train_loss=0.010927 val_loss=0.027204
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 12/60 - train_loss=0.009300 val_loss=0.029239
Epoch 13/60 - train_loss=0.010149 val_loss=0.019363
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth
Epoch 14/60 - train_loss=0.010697 val_loss=0.027323
Epoch 15/60 - train_loss=0.009151 val_loss=0.034233
Epoch 16/60 - train_loss=0.009495 val_loss=0.025497
Epoch 17/60 - train_loss=0.009333 val_loss=0.032353
Epoch 18/60 - train_loss=0.008576 val_loss=0.031793
Epoch 19/60 - train_loss=0.010832 val_loss=0.042664
Epoch 20/60 - train_loss=0.010017 val_loss=0.025646
Epoch 21/60 - train_loss=0.009134 val_loss=0.032221
Epoch 22/60 - train_loss=0.008745 val_loss=0.024065
Epoch 23/60 - train_loss=0.008781 val_loss=0.025748
Early stopping after 23 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/univariate/lstm_Beras_Medium_univariate.pth for final evaluation
Training finished in 1.9 sec

Final test metrics:
MAE: 106.835 Rp/kg
RMSE: 108.124 Rp/kg
MAPE: 0.855 %
sMAPE: 0.851 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Epoch 1/60 - train_loss=0.483567 val_loss=0.036561
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 2/60 - train_loss=0.073929 val_loss=0.071334
Epoch 3/60 - train_loss=0.036693 val_loss=0.024741
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 4/60 - train_loss=0.025774 val_loss=0.022438
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 5/60 - train_loss=0.018244 val_loss=0.019051
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 6/60 - train_loss=0.017216 val_loss=0.032258
Epoch 7/60 - train_loss=0.013741 val_loss=0.025175
Epoch 8/60 - train_loss=0.012402 val_loss=0.019942
Epoch 9/60 - train_loss=0.011193 val_loss=0.019361
Epoch 10/60 - train_loss=0.012863 val_loss=0.034195
Epoch 11/60 - train_loss=0.014177 val_loss=0.015002
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 12/60 - train_loss=0.013192 val_loss=0.014014
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 13/60 - train_loss=0.010098 val_loss=0.018254
Epoch 14/60 - train_loss=0.010665 val_loss=0.019546
Epoch 15/60 - train_loss=0.009032 val_loss=0.018683
Epoch 16/60 - train_loss=0.009033 val_loss=0.016162
Epoch 17/60 - train_loss=0.009013 val_loss=0.011709
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth
Epoch 18/60 - train_loss=0.009408 val_loss=0.017106
Epoch 19/60 - train_loss=0.008122 val_loss=0.019882
Epoch 20/60 - train_loss=0.009067 val_loss=0.015271
Epoch 21/60 - train_loss=0.009743 val_loss=0.012340
Epoch 22/60 - train_loss=0.008790 val_loss=0.015992
Epoch 23/60 - train_loss=0.008355 val_loss=0.015340
Epoch 24/60 - train_loss=0.008413 val_loss=0.022812
Epoch 25/60 - train_loss=0.007499 val_loss=0.014407
Epoch 26/60 - train_loss=0.007370 val_loss=0.023244
Epoch 27/60 - train_loss=0.007121 val_loss=0.013694
Early stopping after 27 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Beras_Medium/multivariate/lstm_Beras_Medium_multivariate.pth for final evaluation
Training finished in 2.1 sec

Final test metrics:
MAE: 116.826 Rp/kg
RMSE: 117.447 Rp/kg
MAPE: 0.935 %
sMAPE: 0.930 %
Directional Accuracy: 0.00 %
Comparison output file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/all_commodity_compare.csv

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

=== Running commodity: Jagung Pipil Kering ===

2026-06-02 15:18:02.139204: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 15:18:02.152693: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 15:18:02.168964: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 15:18:02.173272: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 15:18:02.184342: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Device: cuda
Epoch 1/60 - train_loss=0.888337 val_loss=0.243764
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 2/60 - train_loss=0.353645 val_loss=0.113400
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 3/60 - train_loss=0.236113 val_loss=0.072352
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 4/60 - train_loss=0.155515 val_loss=0.067094
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 5/60 - train_loss=0.099449 val_loss=0.060063
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 6/60 - train_loss=0.075399 val_loss=0.043714
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 7/60 - train_loss=0.061162 val_loss=0.037061
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 8/60 - train_loss=0.061915 val_loss=0.032487
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 9/60 - train_loss=0.057867 val_loss=0.029191
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 10/60 - train_loss=0.048835 val_loss=0.028879
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 11/60 - train_loss=0.054452 val_loss=0.026880
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 12/60 - train_loss=0.047153 val_loss=0.025219
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 13/60 - train_loss=0.045147 val_loss=0.024707
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 14/60 - train_loss=0.050473 val_loss=0.024457
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 15/60 - train_loss=0.048739 val_loss=0.023163
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 16/60 - train_loss=0.048774 val_loss=0.021751
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 17/60 - train_loss=0.041753 val_loss=0.023812
Epoch 18/60 - train_loss=0.041217 val_loss=0.021590
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 19/60 - train_loss=0.040312 val_loss=0.021165
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 20/60 - train_loss=0.041042 val_loss=0.020330
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 21/60 - train_loss=0.037074 val_loss=0.019355
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 22/60 - train_loss=0.038617 val_loss=0.020785
Epoch 23/60 - train_loss=0.038677 val_loss=0.019088
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 24/60 - train_loss=0.039051 val_loss=0.018956
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 25/60 - train_loss=0.037419 val_loss=0.024214
Epoch 26/60 - train_loss=0.048961 val_loss=0.019385
Epoch 27/60 - train_loss=0.044609 val_loss=0.016624
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 28/60 - train_loss=0.035246 val_loss=0.019169
Epoch 29/60 - train_loss=0.039446 val_loss=0.016897
Epoch 30/60 - train_loss=0.039349 val_loss=0.019777
Epoch 31/60 - train_loss=0.031081 val_loss=0.016674
Epoch 32/60 - train_loss=0.034905 val_loss=0.017044
Epoch 33/60 - train_loss=0.031489 val_loss=0.017812
Epoch 34/60 - train_loss=0.035456 val_loss=0.017159
Epoch 35/60 - train_loss=0.039979 val_loss=0.016389
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 36/60 - train_loss=0.036109 val_loss=0.017312
Epoch 37/60 - train_loss=0.040187 val_loss=0.015646
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 38/60 - train_loss=0.035101 val_loss=0.015482
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth
Epoch 39/60 - train_loss=0.035900 val_loss=0.016707
Epoch 40/60 - train_loss=0.032365 val_loss=0.015892
Epoch 41/60 - train_loss=0.028625 val_loss=0.016798
Epoch 42/60 - train_loss=0.028880 val_loss=0.018539
Epoch 43/60 - train_loss=0.027890 val_loss=0.017523
Epoch 44/60 - train_loss=0.027266 val_loss=0.016454
Epoch 45/60 - train_loss=0.035319 val_loss=0.017864
Epoch 46/60 - train_loss=0.031886 val_loss=0.016217
Epoch 47/60 - train_loss=0.035207 val_loss=0.017709
Epoch 48/60 - train_loss=0.031102 val_loss=0.017513
Early stopping after 48 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/univariate/lstm_Jagung_Pipil_Kering_univariate.pth for final evaluation
Training finished in 4.3 sec

Final test metrics:
MAE: 77.850 Rp/kg
RMSE: 79.772 Rp/kg
MAPE: 1.996 %
sMAPE: 2.017 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/60 - train_loss=0.676183 val_loss=0.108464
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Epoch 2/60 - train_loss=0.301849 val_loss=0.085383
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/60 - train_loss=0.176725 val_loss=0.077179
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/60 - train_loss=0.115478 val_loss=0.062264
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/60 - train_loss=0.081347 val_loss=0.062257
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/60 - train_loss=0.063670 val_loss=0.064698
Epoch 7/60 - train_loss=0.062920 val_loss=0.066338
Epoch 8/60 - train_loss=0.055410 val_loss=0.067154
Epoch 9/60 - train_loss=0.057276 val_loss=0.064415
Epoch 10/60 - train_loss=0.048453 val_loss=0.059800
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 11/60 - train_loss=0.050548 val_loss=0.064892
Epoch 12/60 - train_loss=0.047208 val_loss=0.051739
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 13/60 - train_loss=0.047934 val_loss=0.062428
Epoch 14/60 - train_loss=0.045712 val_loss=0.070455
Epoch 15/60 - train_loss=0.050123 val_loss=0.070789
Epoch 16/60 - train_loss=0.043714 val_loss=0.061449
Epoch 17/60 - train_loss=0.043536 val_loss=0.060597
Epoch 18/60 - train_loss=0.042734 val_loss=0.064036
Epoch 19/60 - train_loss=0.042246 val_loss=0.068558
Epoch 20/60 - train_loss=0.046966 val_loss=0.067511
Epoch 21/60 - train_loss=0.042632 val_loss=0.063978
Epoch 22/60 - train_loss=0.039038 val_loss=0.067181
Early stopping after 22 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Jagung_Pipil_Kering/multivariate/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.8 sec

Final test metrics:
MAE: 104.918 Rp/kg
RMSE: 106.431 Rp/kg
MAPE: 2.690 %
sMAPE: 2.653 %
Directional Accuracy: 0.00 %
Comparison output file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/all_commodity_compare.csv

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

=== Running commodity: Kacang Hijau ===

2026-06-02 15:18:15.999288: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 15:18:16.011308: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 15:18:16.026882: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 15:18:16.031576: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 15:18:16.042987: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Device: cuda
Epoch 1/60 - train_loss=0.790066 val_loss=0.020195
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth
Epoch 2/60 - train_loss=0.457239 val_loss=0.006811
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth
Epoch 3/60 - train_loss=0.331964 val_loss=0.000302
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth
Epoch 4/60 - train_loss=0.252033 val_loss=0.000272
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth
Epoch 5/60 - train_loss=0.170500 val_loss=0.000122
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth
Epoch 6/60 - train_loss=0.132472 val_loss=0.001281
Epoch 7/60 - train_loss=0.134353 val_loss=0.000748
Epoch 8/60 - train_loss=0.113073 val_loss=0.000179
Epoch 9/60 - train_loss=0.098895 val_loss=0.000536
Epoch 10/60 - train_loss=0.081909 val_loss=0.000325
Epoch 11/60 - train_loss=0.084062 val_loss=0.000180
Epoch 12/60 - train_loss=0.093837 val_loss=0.000135
Epoch 13/60 - train_loss=0.086639 val_loss=0.000293
Epoch 14/60 - train_loss=0.070779 val_loss=0.000235
Epoch 15/60 - train_loss=0.066638 val_loss=0.000198
Early stopping after 15 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/univariate/lstm_Kacang_Hijau_univariate.pth for final evaluation
Training finished in 1.5 sec

Final test metrics:
MAE: 1.933 Rp/kg
RMSE: 2.164 Rp/kg
MAPE: 0.015 %
sMAPE: 0.015 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Epoch 1/60 - train_loss=0.584981 val_loss=0.027286
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/multivariate/lstm_Kacang_Hijau_multivariate.pth
Epoch 2/60 - train_loss=0.333676 val_loss=0.000536
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/multivariate/lstm_Kacang_Hijau_multivariate.pth
Epoch 3/60 - train_loss=0.238313 val_loss=0.000135
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/multivariate/lstm_Kacang_Hijau_multivariate.pth
Epoch 4/60 - train_loss=0.161439 val_loss=0.001878
Epoch 5/60 - train_loss=0.133258 val_loss=0.001256
Epoch 6/60 - train_loss=0.123578 val_loss=0.002219
Epoch 7/60 - train_loss=0.103688 val_loss=0.000159
Epoch 8/60 - train_loss=0.090899 val_loss=0.000385
Epoch 9/60 - train_loss=0.089259 val_loss=0.000597
Epoch 10/60 - train_loss=0.074464 val_loss=0.001146
Epoch 11/60 - train_loss=0.076975 val_loss=0.000457
Epoch 12/60 - train_loss=0.064086 val_loss=0.000296
Epoch 13/60 - train_loss=0.073371 val_loss=0.000308
Early stopping after 13 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/Kacang_Hijau/multivariate/lstm_Kacang_Hijau_multivariate.pth for final evaluation
Training finished in 1.3 sec

Final test metrics:
MAE: 5.206 Rp/kg
RMSE: 5.315 Rp/kg
MAPE: 0.040 %
sMAPE: 0.040 %
Directional Accuracy: 0.00 %
Comparison output file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/all_commodity_compare.csv

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

All runs finished. Loading comparison CSV:

,commodity,mode,epochs,mae,rmse,mape,smape,directional_acc
0,Beras Premium,univariate,60,319.854,320.032,2.460,2.430,0.0
1,Beras Premium,multivariate,60,494.515,494.543,3.804,3.733,0.0
2,Beras Premium,univariate,60,244.661,244.789,1.882,1.864,0.0
3,Beras Premium,multivariate,60,745.200,745.202,5.732,5.573,0.0
4,Beras Medium,univariate,60,232.873,233.183,1.863,1.846,0.0
5,Beras Medium,multivariate,60,11.611,13.076,0.093,0.093,0.0
6,Jagung Pipil Kering,univariate,60,45.298,48.863,1.161,1.169,0.0
7,Jagung Pipil Kering,multivariate,60,161.012,161.804,4.129,4.044,0.0
8,Kacang Hijau,univariate,60,8.497,10.178,0.065,0.065,0.0
9,Kacang Hijau,multivariate,60,5.028,6.067,0.039,0.039,0.0
10,Beras Premium,univariate,60,118.314,118.418,0.910,0.906,0.0
11,Beras Premium,multivariate,60,700.446,700.475,5.388,5.247,0.0
12,Beras Medium,univariate,60,63.498,64.454,0.508,0.507,0.0
13,Beras Medium,multivariate,60,51.375,52.332,0.411,0.410,0.0
14,Jagung Pipil Kering,univariate,60,97.099,98.252,2.490,2.522,0.0
15,Jagung Pipil Kering,multivariate,60,134.542,135.267,3.450,3.391,0.0
16,Kacang Hijau,univariate,60,11.149,11.421,0.086,0.086,0.0
17,Kacang Hijau,multivariate,60,4.596,4.813,0.035,0.035,0.0
18,Beras Premium,univariate,60,139.256,139.532,1.071,1.065,0.0
19,Beras Premium,multivariate,60,434.223,434.468,3.340,3.285,0.0
20,Beras Medium,univariate,60,106.835,108.124,0.855,0.851,0.0
21,Beras Medium,multivariate,60,116.826,117.447,0.935,0.930,0.0
22,Jagung Pipil Kering,univariate,60,77.850,79.772,1.996,2.017,0.0
23,Jagung Pipil Kering,multivariate,60,104.918,106.431,2.690,2.653,0.0
24,Kacang Hijau,univariate,60,1.933,2.164,0.015,0.015,0.0
25,Kacang Hijau,multivariate,60,5.206,5.315,0.040,0.040,0.0

## Evaluasi Hasil Training
Setelah menjalankan training dari notebook, muat file perbandingan yang tersedia untuk menilai performa dan memilih komoditas yang perlu tuning.

In [21]:
from pathlib import Path
import pandas as pd

project_root = Path('..').resolve()
compare_path = project_root / 'runs' / 'recomputed_compare.csv'
if not compare_path.exists():
    compare_path = project_root / 'runs' / 'all_commodity_compare.csv'

print('Loading comparison file:', compare_path)
if compare_path.exists():
    comp_df = pd.read_csv(compare_path)
    display(comp_df)
    if {'commodity','mode','mae','rmse','smape'}.issubset(comp_df.columns):
        summary = comp_df.pivot(index='commodity', columns='mode', values='mae').reset_index()
        summary.columns.name = None
        display(summary)
else:
    print('No comparison CSV found. Please run the training cell first.')

Loading comparison file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/recomputed_compare.csv

,commodity,mode,epochs,mae,rmse,mape,smape,directional_acc
0,Beras Premium,univariate,60,183.995,184.167,1.415,1.405,0.0
1,Beras Premium,multivariate,60,465.147,465.448,3.578,3.515,0.0
2,Beras Medium,univariate,60,70.425,71.493,0.563,0.562,0.0
3,Beras Medium,multivariate,60,44.176,45.179,0.353,0.353,0.0
4,Jagung Pipil Kering,univariate,60,91.250,93.407,2.340,2.369,0.0
5,Jagung Pipil Kering,multivariate,60,117.196,118.027,3.005,2.960,0.0
6,Kacang Hijau,univariate,60,9.844,10.925,0.076,0.076,0.0
7,Kacang Hijau,multivariate,60,3.378,4.004,0.026,0.026,0.0

             commodity  multivariate  univariate
0         Beras Medium        44.176      70.425
1        Beras Premium       465.147     183.995
2  Jagung Pipil Kering       117.196      91.250
3         Kacang Hijau         3.378       9.844

## Ringkasan Perbandingan Hasil
Selanjutnya, kita tinjau mode terbaik per komoditas menurut MAE dan rata-rata performa global untuk setiap mode.

In [14]:
if compare_path.exists():
    best_by_mae = (
        comp_df.sort_values(['commodity', 'mae'])
        .groupby('commodity', as_index=False)
        .first()
        .loc[:, ['commodity', 'mode', 'mae', 'rmse', 'smape']]
    )
    print('Best mode per commodity menurut MAE:')
    display(best_by_mae)

    agg = comp_df.groupby('mode').agg(
        avg_mae=('mae', 'mean'),
        avg_rmse=('rmse', 'mean'),
        avg_smape=('smape', 'mean'),
    ).reset_index()
    print('Rata-rata performa per mode:')
    display(agg)
else:
    print('No comparison CSV found. Please run the training cell first.')

Best mode per commodity menurut MAE:

             commodity          mode      mae     rmse  smape
0         Beras Medium  multivariate   44.176   45.179  0.353
1        Beras Premium    univariate  183.995  184.167  1.405
2  Jagung Pipil Kering    univariate   91.250   93.407  2.369
3         Kacang Hijau  multivariate    3.378    4.004  0.026

Rata-rata performa per mode:

           mode    avg_mae  avg_rmse  avg_smape
0  multivariate  157.47425  158.1645     1.7135
1    univariate   88.87850   89.9980     1.1030

## Load Data Terproses

Menggunakan `data/processed/price_cleaned.csv` yang dibuat di tahap Data Preparation.

In [15]:
processed_dir = Path('../data/processed')
price_df = pd.read_csv(processed_dir / 'price_cleaned.csv', parse_dates=['Tanggal'])
price_df = price_df.sort_values(['Komoditi', 'Tanggal']).reset_index(drop=True)
price_df.head(3)

       Komoditi    Tanggal  Harga Petani  Harga Pengecer
0  Beras Medium 2022-01-01        8800.0          9000.0
1  Beras Medium 2022-01-02        8800.0          9000.0
2  Beras Medium 2022-01-03        8800.0          9000.0

## Dataset Sequence (Univariat)

Membangun dataset sliding-window untuk target `Harga Petani`. Contoh menggunakan satu komoditas: `Beras Medium`.

In [16]:
class PriceSequenceDataset(Dataset):
    def __init__(self, features: np.ndarray, targets: np.ndarray, seq_len: int, scaler_x=None, scaler_y=None):
        self.seq_len = seq_len
        self.scaler_x = scaler_x or StandardScaler()
        self.scaler_y = scaler_y or StandardScaler()
        self.features = self.scaler_x.fit_transform(features.astype(float))
        self.targets = self.scaler_y.fit_transform(targets.reshape(-1, 1)).ravel()

    def __len__(self):
        return len(self.features) - self.seq_len

    def __getitem__(self, idx):
        x = self.features[idx: idx + self.seq_len]
        y = self.targets[idx + self.seq_len]
        return torch.tensor(x, dtype=torch.float32), torch.tensor(y, dtype=torch.float32)

    def inverse_target(self, y):
        arr = np.array(y).reshape(-1, 1)
        return self.scaler_y.inverse_transform(arr).ravel()

# Select one commodity series
series_name = cfg['commodities'][1]['series_id']  # Beras Medium (index 1)
series = price_df.loc[price_df['Komoditi'] == series_name].set_index('Tanggal')[cfg['preprocessing']['target_col']]
print('Series length for', series_name, len(series))

# Build univariate dataset and dataloaders
features = series.values.reshape(-1, 1).astype(float)
targets = series.values.astype(float)
full_dataset = PriceSequenceDataset(features, targets, seq_len)
print('Univariate feature dimension:', full_dataset.features.shape[1])

n = len(full_dataset)
train_n = int(n * 0.7)
val_n = int(n * 0.15)
test_n = n - train_n - val_n
train_ds, val_ds, test_ds = random_split(full_dataset, [train_n, val_n, test_n], generator=torch.Generator().manual_seed(42))
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)
print('Univariate dataset sizes (train/val/test):', len(train_ds), len(val_ds), len(test_ds))

Series length for Beras Medium 1064
Univariate feature dimension: 1
Univariate dataset sizes (train/val/test): 725 155 156

## Dataset Sequence (Multivariat dengan Fitur Produksi)

Bangun dataset sequence multivariat dengan menambahkan fitur produksi per kuartal sebagai eksogen. Sekarang model dapat melihat pola harga plus data produksi kuartal yang relevan.

In [20]:
prod_df = pd.read_csv(processed_dir / 'production_transformed.csv', parse_dates=['quarter_start'])
prod_df['quarter_start'] = pd.to_datetime(prod_df['quarter_start'])

series_df = price_df.loc[price_df['Komoditi'] == series_name].copy()
series_df['quarter_start'] = series_df['Tanggal'].dt.to_period('Q').dt.to_timestamp()

merged = series_df.merge(
    prod_df,
    left_on=['Komoditi', 'quarter_start'],
    right_on=['Komoditi_Harga', 'quarter_start'],
    how='left'
)

print('Merged shape:', merged.shape)
print('Sample merged columns:', merged.columns.tolist())

exog_cols = [
    c for c in merged.columns
    if c not in ['Tanggal', 'Komoditi', 'quarter_start', 'Komoditi_Harga', cfg['preprocessing']['target_col']]
    and np.issubdtype(merged[c].dtype, np.number)
]
input_cols = [cfg['preprocessing']['target_col']] + exog_cols
print('Input columns for multivariate model:', input_cols)

mv_features = merged[input_cols].ffill().bfill().values.astype(float)
mv_targets = merged[cfg['preprocessing']['target_col']].values.astype(float)
full_dataset_mv = PriceSequenceDataset(mv_features, mv_targets, seq_len)
print('Multivariate feature dimension:', full_dataset_mv.features.shape[1])

n_mv = len(full_dataset_mv)
train_n_mv = int(n_mv * 0.7)
val_n_mv = int(n_mv * 0.15)
test_n_mv = n_mv - train_n_mv - val_n_mv
train_ds_mv, val_ds_mv, test_ds_mv = random_split(full_dataset_mv, [train_n_mv, val_n_mv, test_n_mv], generator=torch.Generator().manual_seed(42))
train_loader_mv = DataLoader(train_ds_mv, batch_size=batch_size, shuffle=True)
val_loader_mv = DataLoader(val_ds_mv, batch_size=batch_size, shuffle=False)
test_loader_mv = DataLoader(test_ds_mv, batch_size=batch_size, shuffle=False)
print('Multivariate dataset sizes (train/val/test):', len(train_ds_mv), len(val_ds_mv), len(test_ds_mv))

Merged shape: (1064, 12)
Sample merged columns: ['Komoditi_x', 'Tanggal', 'Harga Petani', 'Harga Pengecer', 'quarter_start', 'Komoditi_y', 'tahun', 'triwulan', 'Luas Panen', 'Produktivitas', 'Produksi', 'Komoditi_Harga']
Input columns for multivariate model: ['Harga Petani', 'Harga Pengecer', 'tahun', 'triwulan', 'Luas Panen', 'Produktivitas', 'Produksi']
Multivariate feature dimension: 7
Multivariate dataset sizes (train/val/test): 725 155 156

## Perbandingan Metrik: Univariat vs Multivariat

Di bawah ini kita akan melatih dua model LSTM pendek dengan konfigurasi yang sama, lalu membandingkan metrik pada test set untuk model univariat dan multivariat. Ini membantu mengevaluasi apakah fitur produksi eksogen memberikan nilai tambah pada prediksi harga.

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import sys
from pathlib import Path as _Path
# ensure project root is on sys.path so `src` package is importable from notebooks
sys.path.insert(0, str(_Path('..').resolve()))
from src.models.base_model import BaseLSTMModel

def directional_accuracy(y_true, y_pred):
    dir_true = np.sign(np.diff(y_true))
    dir_pred = np.sign(np.diff(y_pred))
    return 100.0 * np.mean(dir_true == dir_pred)

def train_model(model, loader, epochs, device, lr):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(device)
            yb = yb.to(device).unsqueeze(-1)
            optimizer.zero_grad()
            loss = loss_fn(model(xb), yb)
            loss.backward()
            optimizer.step()
            total_loss += loss.item() * xb.size(0)
    return total_loss / len(loader.dataset)

def evaluate_model(model, loader, scaler_y):
    model.eval()
    y_true = []
    y_pred = []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            preds = model(xb).cpu().numpy().ravel()
            y_pred.extend(preds.tolist())
            y_true.extend(yb.numpy().ravel().tolist())
    y_true = scaler_y.inverse_transform(np.array(y_true).reshape(-1, 1)).ravel()
    y_pred = scaler_y.inverse_transform(np.array(y_pred).reshape(-1, 1)).ravel()
    return {
        "mae": mean_absolute_error(y_true, y_pred),
        "rmse": mean_squared_error(y_true, y_pred, squared=False),
        "mape": np.mean(np.abs((y_pred - y_true) / np.where(y_true == 0, 1e-8, y_true))) * 100.0,
        "smape": np.mean(2.0 * np.abs(y_pred - y_true) / (np.abs(y_pred) + np.abs(y_true) + 1e-8)) * 100.0,
        "directional_accuracy": directional_accuracy(y_true, y_pred),
    }

# Create separate univariate loaders for comparison
n_uni = len(full_dataset)
train_n_uni = int(n_uni * 0.7)
val_n_uni = int(n_uni * 0.15)
test_n_uni = n_uni - train_n_uni - val_n_uni
train_ds_uni, val_ds_uni, test_ds_uni = random_split(full_dataset, [train_n_uni, val_n_uni, test_n_uni], generator=torch.Generator().manual_seed(42))
train_loader_uni = DataLoader(train_ds_uni, batch_size=batch_size, shuffle=True)
val_loader_uni = DataLoader(val_ds_uni, batch_size=batch_size, shuffle=False)
test_loader_uni = DataLoader(test_ds_uni, batch_size=batch_size, shuffle=False)

uni_model = BaseLSTMModel(input_size=full_dataset.features.shape[1], hidden_size=hidden_size, num_layers=num_layers, dropout=dropout).to(device)
mv_model = BaseLSTMModel(input_size=full_dataset_mv.features.shape[1], hidden_size=hidden_size, num_layers=num_layers, dropout=dropout).to(device)

train_model(uni_model, train_loader_uni, epochs, device, lr)
train_model(mv_model, train_loader_mv, epochs, device, lr)

uni_metrics = evaluate_model(uni_model, test_loader_uni, full_dataset.scaler_y)
mv_metrics = evaluate_model(mv_model, test_loader_mv, full_dataset_mv.scaler_y)

comparison_df = pd.DataFrame([
    {"mode": "univariat", **uni_metrics, "commodity": series_name},
    {"mode": "multivariat", **mv_metrics, "commodity": series_name},
])
display(comparison_df)

/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

,mode,mae,rmse,mape,smape,directional_accuracy,commodity
0,univariat,94.435084,200.487189,0.851274,0.854015,89.677419,Beras Medium
1,multivariat,101.253440,197.313502,0.942984,0.944360,86.451613,Beras Medium

## Insight dari Notebook Modeling

**Ringkasan Temuan Utama**:

- Model multivariat yang menambahkan fitur produksi kuartal menunjukkan potensi peningkatan informasi dibandingkan model univariat yang hanya menggunakan harga historis. Perbedaan performa perlu divalidasi lebih luas menggunakan pelatihan yang lebih lama dan cross-validation.

- Penggabungan data produksi dilakukan dengan kunci `Komoditi` dan `quarter_start`; pastikan setiap pengamatan harga disejajarkan ke kuartal produksi yang benar agar fitur eksogen relevan.

- `PriceSequenceDataset` dibuat fleksibel untuk menerima input 1-dimensi atau multi-dimensi sehingga pipeline dapat digunakan ulang untuk kedua skenario tanpa perubahan arsitektur dataset.

- Catatan eksperimen: percobaan singkat di notebook menggunakan `epochs` kecil (demo). Untuk penilaian nyata, jalankan pelatihan penuh (mis. epochs=60+), simpan kurva training/validation, dan gunakan metric-driven early stopping.

- Rekomendasi praktis:
  1. Lakukan perbandingan terstandardisasi univariat vs multivariat per komoditas dan laporkan MAE/RMSE serta sMAPE.
  2. Tambahkan fitur lag, seasonality (sin/cos) dan flag libur untuk meningkatkan sinyal temporal.
  3. Jalankan Optuna per komoditas untuk menemukan konfigurasi LSTM terbaik dan simpan studi serta checkpoint.
  4. Validasi akhir pada horizon produksi nyata sebelum mempertimbangkan deployment.