# 06_Evaluation

Dokumentasi fase Evaluation. Metode evaluasi performa dan benchmark model berdasarkan MAE, RMSE, MAPE, sMAPE, dan Directional Accuracy.

## Load comparison results and summary

Sel yang memuat semua file perbandingan hasil eksperimen (jika tersedia) dan menyajikan ringkasan metrik per komoditas. Jika file tidak ditemukan, jalankan `notebooks/05_Modeling_v2.ipynb` atau skrip `src/train.py` untuk menghasilkan `runs/*_compare.csv`.

In [48]:
from pathlib import Path
import pandas as pd
project_root = Path('..').resolve()
compare_paths = [
    project_root / 'runs' / 'recomputed_compare.csv',
    project_root / 'runs' / 'all_commodity_optuna_summary.csv',
    project_root / 'runs' / 'all_commodity_compare.csv',
]
compare_path = next((p for p in compare_paths if p.exists()), None)

if compare_path is None:
    print('No comparison CSV found. Expected one of:')
    for p in compare_paths:
        print(' -', p)
else:
    print('Loading comparison CSV from', compare_path)
    comp = pd.read_csv(compare_path)
    display(comp)

    if compare_path.name == 'all_commodity_final_compare.csv':
        comp = comp.copy()
        if 'mae_improvement_vs_baseline_multivariate' in comp.columns:
            comp['mae_improvement_vs_baseline_multivariate'] = comp['mae_improvement_vs_baseline_multivariate'].round(3)
            comp['rmse_improvement_vs_baseline_multivariate'] = comp['rmse_improvement_vs_baseline_multivariate'].round(3)
            comp['smape_improvement_vs_baseline_multivariate'] = comp['smape_improvement_vs_baseline_multivariate'].round(3)
            display(comp.sort_values('mae_improvement_vs_baseline_multivariate', ascending=False))
            print('')
            print('Insight summary:')
            if (comp['mae_improvement_vs_baseline_multivariate'] > 0).all():
                print('Optuna retrained multivariate models improved MAE for all commodities versus the earlier baseline multivariate runs.')
            else:
                degraded = comp[comp['mae_improvement_vs_baseline_multivariate'] < 0]['commodity'].tolist()
                print('Commodities with worse Optuna multivariate results than baseline multivariate:', degraded)
            tune_recs = comp[comp['mae_improvement_vs_baseline_multivariate'] < 0]['commodity'].tolist()
            if len(tune_recs) > 0:
                print('Recommend a second investigation/tuning pass for:', tune_recs)
        else:
            print('Final compare file is missing improvement columns; falling back to per-mode comparison logic.')
            if {'mode', 'commodity', 'mae', 'rmse', 'smape'}.issubset(comp.columns):
                uni = comp[comp['mode'] == 'univariate'].set_index('commodity')
                mv = comp[comp['mode'] == 'multivariate'].set_index('commodity')
                merged = uni.join(mv, lsuffix='_uni', rsuffix='_mv')
                merged = merged.dropna()
                merged['mae_delta'] = merged['mae_uni'] - merged['mae_mv']
                merged['rmse_delta'] = merged['rmse_uni'] - merged['rmse_mv']
                merged['smape_delta'] = merged['smape_uni'] - merged['smape_mv']
                summary = merged[['mae_uni','mae_mv','mae_delta','rmse_uni','rmse_mv','rmse_delta','smape_uni','smape_mv','smape_delta']].reset_index()
                summary = summary.sort_values('mae_delta', ascending=False)
                display(summary)
                tune_recs = summary[(summary['mae_delta'] < 0) | (summary['mae_delta'].abs() < 1.0)]['commodity'].tolist()
                print('Recommended commodities for hyperparameter tuning (multivariate worse or similar):', tune_recs)
            else:
                print('Unable to compute fallback summary from the current file structure.')
                tune_recs = []
    elif compare_path.name == 'all_commodity_optuna_summary.csv':
        print('This file contains final Optuna retrain metrics for each commodity. To compare against baseline multivariate results, load all_commodity_final_compare.csv.')
        tune_recs = []
    else:
        uni = comp[comp['mode'] == 'univariate'].set_index('commodity')
        mv = comp[comp['mode'] == 'multivariate'].set_index('commodity')
        merged = uni.join(mv, lsuffix='_uni', rsuffix='_mv')
        merged = merged.dropna()
        merged['mae_delta'] = merged['mae_uni'] - merged['mae_mv']
        merged['rmse_delta'] = merged['rmse_uni'] - merged['rmse_mv']
        merged['smape_delta'] = merged['smape_uni'] - merged['smape_mv']
        summary = merged[['mae_uni','mae_mv','mae_delta','rmse_uni','rmse_mv','rmse_delta','smape_uni','smape_mv','smape_delta']].reset_index()
        summary = summary.sort_values('mae_delta', ascending=False)
        display(summary)
        tune_recs = summary[(summary['mae_delta'] < 0) | (summary['mae_delta'].abs() < 1.0)]['commodity'].tolist()
        print('Recommended commodities for hyperparameter tuning (multivariate worse or similar):', tune_recs)
    globals()['tune_recs'] = tune_recs

Loading comparison CSV from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/recomputed_compare.csv

,commodity,mode,epochs,mae,rmse,mape,smape,directional_acc
0,Beras Premium,univariate,60,183.995,184.167,1.415,1.405,0.0
1,Beras Premium,multivariate,60,465.147,465.448,3.578,3.515,0.0
2,Beras Medium,univariate,60,70.425,71.493,0.563,0.562,0.0
3,Beras Medium,multivariate,60,44.176,45.179,0.353,0.353,0.0
4,Jagung Pipil Kering,univariate,60,91.250,93.407,2.340,2.369,0.0
5,Jagung Pipil Kering,multivariate,60,117.196,118.027,3.005,2.960,0.0
6,Kacang Hijau,univariate,60,9.844,10.925,0.076,0.076,0.0
7,Kacang Hijau,multivariate,60,3.378,4.004,0.026,0.026,0.0

,commodity,mae_uni,mae_mv,mae_delta,rmse_uni,rmse_mv,rmse_delta,smape_uni,smape_mv,smape_delta
1,Beras Medium,70.425,44.176,26.249,71.493,45.179,26.314,0.562,0.353,0.209
3,Kacang Hijau,9.844,3.378,6.466,10.925,4.004,6.921,0.076,0.026,0.050
2,Jagung Pipil Kering,91.250,117.196,-25.946,93.407,118.027,-24.620,2.369,2.960,-0.591
0,Beras Premium,183.995,465.147,-281.152,184.167,465.448,-281.281,1.405,3.515,-2.110

Recommended commodities for hyperparameter tuning (multivariate worse or similar): ['Jagung Pipil Kering', 'Beras Premium']

In [ ]:
# Jalankan baseline ulang untuk satu komoditas dari notebook jika diperlukan
run_baseline = True
if run_baseline:
    import subprocess, sys
    from pathlib import Path
    project_root = Path('..').resolve()
    baseline_cmd = [
        sys.executable,
        str(project_root / 'src' / 'train.py'),
        '--commodity', 'Beras Medium',
        '--mode', 'both',
        '--epochs', '60',
        '--device', 'cpu',
        '--log-csv', str(project_root / 'runs' / 'recomputed_metrics_Beras_Medium.csv'),
        '--compare-csv', str(project_root / 'runs' / 'recomputed_compare.csv'),
        '--early-stopping-patience', '5',
    ]
    print('Running baseline recompute for Beras Medium:')
    print(' '.join(baseline_cmd))
    subprocess.run(baseline_cmd, cwd=str(project_root), check=True)
    print('Recompute finished. Refresh the comparison cell to load updated results.')

Running baseline recompute for Beras Medium:
/home/rna_13/anaconda3/envs/rapids-24.10/bin/python /home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py --commodity Beras Medium --mode both --epochs 60 --device cpu --log-csv /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/recomputed_metrics_Beras_Medium.csv --compare-csv /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/recomputed_compare.csv --early-stopping-patience 5

2026-06-02 17:23:42.813906: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 17:23:42.827917: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 17:23:42.847154: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 17:23:42.852843: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 17:23:42.867222: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Device: cpu
Epoch 1/60 - train_loss=0.781591 val_loss=0.927479
  Saved best model to models/lstm_Beras_Medium_univariate.pth
Epoch 2/60 - train_loss=0.213813 val_loss=0.119735
  Saved best model to models/lstm_Beras_Medium_univariate.pth
Epoch 3/60 - train_loss=0.076939 val_loss=0.029793
  Saved best model to models/lstm_Beras_Medium_univariate.pth
Epoch 4/60 - train_loss=0.046077 val_loss=0.030103
Epoch 5/60 - train_loss=0.035871 val_loss=0.033563
Epoch 6/60 - train_loss=0.029428 val_loss=0.038772
Epoch 7/60 - train_loss=0.024481 val_loss=0.045677
Epoch 8/60 - train_loss=0.019829 val_loss=0.036114
Early stopping after 8 epochs with no improvement for 5 epochs.
Loading best checkpoint from models/lstm_Beras_Medium_univariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 125.748 Rp/kg
RMSE: 126.135 Rp/kg
MAPE: 1.006 %
sMAPE: 1.001 %
Directional Accuracy: 0.00 %
Device: cpu

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Epoch 1/60 - train_loss=0.443588 val_loss=0.170650
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 2/60 - train_loss=0.069214 val_loss=0.040356
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 3/60 - train_loss=0.034305 val_loss=0.024583
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 4/60 - train_loss=0.024771 val_loss=0.019724
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 5/60 - train_loss=0.018878 val_loss=0.021515
Epoch 6/60 - train_loss=0.015273 val_loss=0.022236
Epoch 7/60 - train_loss=0.016531 val_loss=0.018013
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 8/60 - train_loss=0.012886 val_loss=0.016527
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 9/60 - train_loss=0.012918 val_loss=0.017274
Epoch 10/60 - train_loss=0.012538 val_loss=0.018044
Epoch 11/60 - train_loss=0.009859 val_loss=0.015003
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 12/60 - train_loss=0.010974 val_loss=0.013375
  Saved best model to models/lstm_Beras_Medium_multivariate.pth
Epoch 13/60 - train_loss=0.011700 val_loss=0.014735
Epoch 14/60 - train_loss=0.010253 val_loss=0.016808
Epoch 15/60 - train_loss=0.009551 val_loss=0.014288
Epoch 16/60 - train_loss=0.008359 val_loss=0.016223
Epoch 17/60 - train_loss=0.008349 val_loss=0.014607
Early stopping after 17 epochs with no improvement for 5 epochs.
Loading best checkpoint from models/lstm_Beras_Medium_multivariate.pth for final evaluation
Training finished in 10.7 sec

Final test metrics:
MAE: 84.633 Rp/kg
RMSE: 85.237 Rp/kg
MAPE: 0.677 %
sMAPE: 0.675 %
Directional Accuracy: 0.00 %
Comparison output file: /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/recomputed_compare.csv

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Recompute finished. Refresh the comparison cell to load updated results.

## Evaluation Insight

`runs/recomputed_compare.csv` sekarang adalah baseline yang digunakan untuk evaluasi. Ini adalah hasil terkini dari pelatihan ulang baseline menggunakan `src/train.py`, dan menggantikan potensi metrik lama yang tidak lagi konsisten dengan kondisi kode saat ini.

- `Beras Medium`: multivariat saat ini lebih baik dari univariat, dengan MAE sekitar 44.2 vs 70.4. Ini menandakan bahwa fitur produksi dan seasonalitas memberikan nilai tambah yang nyata untuk komoditas ini.
- `Kacang Hijau`: multivariat juga lebih kuat, dengan MAE sekitar 3.4 vs 9.8. Fitur eksogen tampaknya membantu stabilisasi prediksi harga kecil ini.
- `Jagung Pipil Kering`: baseline multivariat saat ini lebih buruk daripada univariat (MAE sekitar 117 vs 91), sehingga perlu ditinjau kembali fitur input atau konfigurasi LSTM untuk komoditas ini.
- `Beras Premium`: baseline multivariat saat ini jauh lebih buruk daripada univariat (MAE sekitar 465 vs 184), yang menunjukkan bahwa pipeline multivariat saat ini tidak terkalibrasi untuk komoditas ini.

Rekomendasi:
- Gunakan `runs/recomputed_compare.csv` sebagai baseline evaluasi saat ini.
- Fokuskan investigasi pada `Beras Premium` dan `Jagung Pipil Kering` untuk memperbaiki fitur multivariat atau target scaling.
- `Beras Medium` tetap prioritas untuk deployment lanjut karena multivariat memberikan peningkatan nyata di baseline terkini.
- Pastikan `src/train.py` di notebook memuat checkpoint terbaik sebelum evaluasi, dan gunakan `run_baseline = True` hanya jika Anda ingin merekomputasi ulang metrik dari notebook.

## Optuna Hyperparameter Tuning (opsional)

Sel ini akan menjalankan Optuna untuk komoditas yang direkomendasikan di atas. Atur `run_optuna=True` dan `trials` sesuai kebutuhan. Hati-hati: menjalankan Optuna memicu pelatihan beberapa kali dan membutuhkan waktu/compute.

In [51]:
import subprocess, sys
from pathlib import Path
run_optuna = True  # ubah ke True untuk menjalankan tuning
trials = 50
project_root = Path('..').resolve()

if run_optuna:
	if 'tune_recs' not in globals() or len(tune_recs) == 0:
		print('No recommended commodities found. Set `tune_list` manually, or run the previous cell to compute recommendations.')
		tune_list = []
	else:
		tune_list = tune_recs

	for commodity in tune_list:
		print('\n--- Running Optuna for', commodity, '---')
		cmd = [
			sys.executable,
			str(project_root / 'src' / 'train.py'),
			'--commodity', commodity,
			'--mode', 'multivariate',
			'--optuna',
			'--optuna-trials', str(trials),
			'--log-dir', str(project_root / f'runs/optuna/{commodity.replace(" ","_")}'),
			'--log-csv', str(project_root / 'runs' / 'optuna_metrics.csv'),
		]
		try:
			subprocess.run(cmd, cwd=str(project_root), check=True)
		except subprocess.CalledProcessError as e:
			print('Optuna run failed for', commodity, e)
else:
	print('Optuna tuning skipped (set run_optuna=True to enable)')

--- Running Optuna for Jagung Pipil Kering ---

2026-06-02 17:26:56.677857: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 17:26:56.692382: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 17:26:56.709045: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 17:26:56.713612: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 17:26:56.726061: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2026-06-02 17:26:59,131] A new study created in memory with name: no-name-a4e14e31-4fe4-4fc1-911e-efdeb53c8b21

Device: cuda
Epoch 1/10 - train_loss=1.180363 val_loss=0.564326
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=1.133637 val_loss=0.552243
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=1.092050 val_loss=0.539975
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=1.043296 val_loss=0.519588
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.994262 val_loss=0.494774
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.925604 val_loss=0.461417
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.839400 val_loss=0.418005
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.728629 val_loss=0.360454
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.620636 val_loss=0.300432
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.512824 val_loss=0.245035
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.1 sec

Final test metrics:
MAE: 434.965 Rp/kg
RMSE: 435.000 Rp/kg
MAPE: 11.153 %
sMAPE: 10.564 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.500481 val_loss=0.096234
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:01,070] Trial 0 finished with value: 0.2450353242271575 and parameters: {'hidden_size': 23, 'num_layers': 2, 'dropout': 0.2707204436485321, 'lr': 0.00022053401649864158}. Best is trial 0 with value: 0.2450353242271575.

Epoch 2/10 - train_loss=0.153787 val_loss=0.042464
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.091185 val_loss=0.052363
Epoch 4/10 - train_loss=0.063790 val_loss=0.049121
Epoch 5/10 - train_loss=0.060344 val_loss=0.040534
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.052188 val_loss=0.033173
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.053321 val_loss=0.030742
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.039711 val_loss=0.046194
Epoch 9/10 - train_loss=0.060069 val_loss=0.031242
Epoch 10/10 - train_loss=0.050014 val_loss=0.041938
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 13.266 Rp/kg
RMSE: 16.234 Rp/kg
MAPE: 0.340 %
sMAPE: 0.340 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:01,870] Trial 1 finished with value: 0.03074165095229962 and parameters: {'hidden_size': 78, 'num_layers': 2, 'dropout': 0.31285089292743573, 'lr': 0.0035976845199959676}. Best is trial 1 with value: 0.03074165095229962.

Epoch 1/10 - train_loss=0.609723 val_loss=0.271654
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.238624 val_loss=0.103615
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.158658 val_loss=0.118147
Epoch 4/10 - train_loss=0.110729 val_loss=0.113795
Epoch 5/10 - train_loss=0.083274 val_loss=0.089187
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.062310 val_loss=0.087688
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.052199 val_loss=0.077096
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.046875 val_loss=0.074055
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.049589 val_loss=0.066063
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.046033 val_loss=0.068436
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 179.190 Rp/kg
RMSE: 180.244 Rp/kg
MAPE: 4.595 %
sMAPE: 4.490 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:02,609] Trial 2 finished with value: 0.06606275575300355 and parameters: {'hidden_size': 63, 'num_layers': 1, 'dropout': 0.08490944140793122, 'lr': 0.0013495607142531287}. Best is trial 1 with value: 0.03074165095229962.

Epoch 1/10 - train_loss=1.172141 val_loss=0.356053
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.977416 val_loss=0.322701
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.777625 val_loss=0.290212
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.591422 val_loss=0.257785
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.413675 val_loss=0.225539
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.328229 val_loss=0.193506
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.285635 val_loss=0.165944
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.243197 val_loss=0.145329
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.217650 val_loss=0.127904
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.195554 val_loss=0.118075
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 104.747 Rp/kg
RMSE: 104.945 Rp/kg
MAPE: 2.686 %
sMAPE: 2.650 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=1.099111 val_loss=0.483307
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.692217 val_loss=0.403866
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:03,342] Trial 3 finished with value: 0.11807455262864258 and parameters: {'hidden_size': 117, 'num_layers': 1, 'dropout': 0.4500174368834362, 'lr': 0.00014776292343117374}. Best is trial 1 with value: 0.03074165095229962.

Epoch 3/10 - train_loss=0.393521 val_loss=0.088206
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.320758 val_loss=0.106527
Epoch 5/10 - train_loss=0.260088 val_loss=0.102195
Epoch 6/10 - train_loss=0.206691 val_loss=0.094528
Epoch 7/10 - train_loss=0.152241 val_loss=0.091593
Epoch 8/10 - train_loss=0.116646 val_loss=0.102699
Epoch 9/10 - train_loss=0.090931 val_loss=0.088375
Epoch 10/10 - train_loss=0.066438 val_loss=0.094563
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 50.221 Rp/kg
RMSE: 50.688 Rp/kg
MAPE: 1.288 %
sMAPE: 1.279 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:04,032] Trial 4 finished with value: 0.08820561956225047 and parameters: {'hidden_size': 77, 'num_layers': 3, 'dropout': 0.4287329686191725, 'lr': 0.0004296780696576416}. Best is trial 1 with value: 0.03074165095229962.

Device: cuda
Epoch 1/10 - train_loss=1.029833 val_loss=0.310700
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.622447 val_loss=0.263483
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.318679 val_loss=0.207381
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.239854 val_loss=0.132209
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.180989 val_loss=0.100407
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.148909 val_loss=0.091980
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.118908 val_loss=0.090764
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.101328 val_loss=0.083772
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.082628 val_loss=0.078279
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.070484 val_loss=0.074805
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 80.552 Rp/kg
RMSE: 80.978 Rp/kg
MAPE: 2.065 %
sMAPE: 2.044 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:04,787] Trial 5 finished with value: 0.07480512835103925 and parameters: {'hidden_size': 128, 'num_layers': 1, 'dropout': 0.020803165957899383, 'lr': 0.00028936775130272734}. Best is trial 1 with value: 0.03074165095229962.

Epoch 1/10 - train_loss=0.933462 val_loss=0.358135
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.363810 val_loss=0.084149
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.275282 val_loss=0.091127
Epoch 4/10 - train_loss=0.181238 val_loss=0.083476
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.103693 val_loss=0.101163
Epoch 6/10 - train_loss=0.097597 val_loss=0.099803
Epoch 7/10 - train_loss=0.073426 val_loss=0.093623
Epoch 8/10 - train_loss=0.062322 val_loss=0.095738
Epoch 9/10 - train_loss=0.059642 val_loss=0.096496
Epoch 10/10 - train_loss=0.067807 val_loss=0.073994
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 136.780 Rp/kg
RMSE: 138.035 Rp/kg
MAPE: 3.507 %
sMAPE: 3.571 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:05,497] Trial 6 finished with value: 0.07399395463608242 and parameters: {'hidden_size': 35, 'num_layers': 2, 'dropout': 0.335673231539425, 'lr': 0.0019003783785763748}. Best is trial 1 with value: 0.03074165095229962.

Epoch 1/10 - train_loss=1.087347 val_loss=0.354725
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.805393 val_loss=0.318375
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.562773 val_loss=0.279585
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.351604 val_loss=0.241578
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.246319 val_loss=0.204882
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.200819 val_loss=0.179390
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.170510 val_loss=0.170286
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.147481 val_loss=0.169119
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.127959 val_loss=0.167604
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.110359 val_loss=0.163296
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.6 sec

Final test metrics:
MAE: 301.798 Rp/kg
RMSE: 301.876 Rp/kg
MAPE: 7.738 %
sMAPE: 7.450 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.623864 val_loss=0.101814
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:06,090] Trial 7 finished with value: 0.16329594026898864 and parameters: {'hidden_size': 83, 'num_layers': 1, 'dropout': 0.3204750820781562, 'lr': 0.0002747247241218506}. Best is trial 1 with value: 0.03074165095229962.

Epoch 2/10 - train_loss=0.250013 val_loss=0.091472
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.115035 val_loss=0.076747
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.109108 val_loss=0.067610
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.071339 val_loss=0.070375
Epoch 6/10 - train_loss=0.049087 val_loss=0.064137
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.049631 val_loss=0.050846
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.053599 val_loss=0.050884
Epoch 9/10 - train_loss=0.042084 val_loss=0.041943
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.039113 val_loss=0.045197
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 317.731 Rp/kg
RMSE: 318.508 Rp/kg
MAPE: 8.147 %
sMAPE: 8.495 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=1.050921 val_loss=0.307850
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:06,919] Trial 8 finished with value: 0.041943341197066046 and parameters: {'hidden_size': 42, 'num_layers': 3, 'dropout': 0.14424876160980754, 'lr': 0.005280589042865901}. Best is trial 1 with value: 0.03074165095229962.

Epoch 2/10 - train_loss=0.517874 val_loss=0.199326
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.310228 val_loss=0.097167
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.247200 val_loss=0.098773
Epoch 5/10 - train_loss=0.174435 val_loss=0.101859
Epoch 6/10 - train_loss=0.136867 val_loss=0.085446
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.100472 val_loss=0.087438
Epoch 8/10 - train_loss=0.077505 val_loss=0.082429
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.061992 val_loss=0.080136
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.101342 val_loss=0.076282
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 153.472 Rp/kg
RMSE: 153.918 Rp/kg
MAPE: 3.935 %
sMAPE: 3.859 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:07,800] Trial 9 finished with value: 0.07628201784111967 and parameters: {'hidden_size': 118, 'num_layers': 2, 'dropout': 0.4624598184650408, 'lr': 0.0003585346366482206}. Best is trial 1 with value: 0.03074165095229962.

Epoch 1/10 - train_loss=0.498680 val_loss=0.101718
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.216520 val_loss=0.053990
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.085127 val_loss=0.069186
Epoch 4/10 - train_loss=0.069661 val_loss=0.043241
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.067903 val_loss=0.057055
Epoch 6/10 - train_loss=0.047266 val_loss=0.052519
Epoch 7/10 - train_loss=0.045875 val_loss=0.021494
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.045810 val_loss=0.025497
Epoch 9/10 - train_loss=0.038958 val_loss=0.022824
Epoch 10/10 - train_loss=0.036999 val_loss=0.022803
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 109.200 Rp/kg
RMSE: 109.710 Rp/kg
MAPE: 2.800 %
sMAPE: 2.840 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.485146 val_loss=0.068401
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.082538 val_loss=0.059276
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:08,759] Trial 10 finished with value: 0.021493907107401695 and parameters: {'hidden_size': 99, 'num_layers': 3, 'dropout': 0.19941222597560465, 'lr': 0.007630245857003952}. Best is trial 10 with value: 0.021493907107401695.

Epoch 3/10 - train_loss=0.077251 val_loss=0.055694
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.068287 val_loss=0.030218
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.059639 val_loss=0.024007
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.055748 val_loss=0.033836
Epoch 7/10 - train_loss=0.049463 val_loss=0.025595
Epoch 8/10 - train_loss=0.050229 val_loss=0.025592
Epoch 9/10 - train_loss=0.043462 val_loss=0.024418
Epoch 10/10 - train_loss=0.037349 val_loss=0.019985
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 191.143 Rp/kg
RMSE: 192.831 Rp/kg
MAPE: 4.901 %
sMAPE: 5.027 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.618265 val_loss=0.654921
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.293483 val_loss=0.104993
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:09,587] Trial 11 finished with value: 0.019984720645481673 and parameters: {'hidden_size': 97, 'num_layers': 3, 'dropout': 0.19190225572119912, 'lr': 0.008213888939547791}. Best is trial 11 with value: 0.019984720645481673.

Epoch 3/10 - train_loss=0.126467 val_loss=0.073890
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.061238 val_loss=0.049959
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.055900 val_loss=0.053166
Epoch 6/10 - train_loss=0.044585 val_loss=0.035505
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.043095 val_loss=0.043859
Epoch 8/10 - train_loss=0.039366 val_loss=0.049563
Epoch 9/10 - train_loss=0.047577 val_loss=0.044202
Epoch 10/10 - train_loss=0.043872 val_loss=0.053173
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:10,364] Trial 12 finished with value: 0.035504760996749006 and parameters: {'hidden_size': 98, 'num_layers': 3, 'dropout': 0.2002214643857744, 'lr': 0.00998216104222226}. Best is trial 11 with value: 0.019984720645481673.

Training finished in 0.7 sec

Final test metrics:
MAE: 36.913 Rp/kg
RMSE: 39.927 Rp/kg
MAPE: 0.946 %
sMAPE: 0.952 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.684671 val_loss=0.109254
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.179250 val_loss=0.169837
Epoch 3/10 - train_loss=0.121127 val_loss=0.171220
Epoch 4/10 - train_loss=0.075414 val_loss=0.172873
Epoch 5/10 - train_loss=0.053038 val_loss=0.075912
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.050388 val_loss=0.102205
Epoch 7/10 - train_loss=0.046330 val_loss=0.154958
Epoch 8/10 - train_loss=0.039419 val_loss=0.129032
Epoch 9/10 - train_loss=0.044398 val_loss=0.131380
Epoch 10/10 - train_loss=0.055439 val_loss=0.111931
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 216.164 Rp/kg
RMSE: 216.239 Rp/kg
MAPE: 5.543 %
sMAPE: 5.701 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:11,208] Trial 13 finished with value: 0.07591204717755318 and parameters: {'hidden_size': 103, 'num_layers': 3, 'dropout': 0.2025454599379257, 'lr': 0.009905512995278738}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.559066 val_loss=0.077615
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.237489 val_loss=0.071571
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.114680 val_loss=0.138271
Epoch 4/10 - train_loss=0.082165 val_loss=0.088398
Epoch 5/10 - train_loss=0.062610 val_loss=0.136229
Epoch 6/10 - train_loss=0.050747 val_loss=0.152191
Epoch 7/10 - train_loss=0.049177 val_loss=0.144408
Epoch 8/10 - train_loss=0.050619 val_loss=0.115968
Epoch 9/10 - train_loss=0.048458 val_loss=0.118534
Epoch 10/10 - train_loss=0.044169 val_loss=0.049394
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 148.517 Rp/kg
RMSE: 149.190 Rp/kg
MAPE: 3.808 %
sMAPE: 3.736 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.672030 val_loss=0.092829
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.356397 val_loss=0.092908

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:12,075] Trial 14 finished with value: 0.04939375934538556 and parameters: {'hidden_size': 97, 'num_layers': 3, 'dropout': 0.21258119674655485, 'lr': 0.004408198658738433}. Best is trial 11 with value: 0.019984720645481673.

Epoch 3/10 - train_loss=0.229703 val_loss=0.087867
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.117901 val_loss=0.090942
Epoch 5/10 - train_loss=0.115469 val_loss=0.072418
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.096817 val_loss=0.058889
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.064681 val_loss=0.066548
Epoch 8/10 - train_loss=0.063631 val_loss=0.056698
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.072694 val_loss=0.054611
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.048876 val_loss=0.051090
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:10,102] Trial 15 finished with value: 0.05109022675888307 and parameters: {'hidden_size': 60, 'num_layers': 3, 'dropout': 0.11140508348002168, 'lr': 0.0020376313303213487}. Best is trial 11 with value: 0.019984720645481673.

Training finished in -2.0 sec

Final test metrics:
MAE: 16.659 Rp/kg
RMSE: 19.380 Rp/kg
MAPE: 0.427 %
sMAPE: 0.428 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.519855 val_loss=0.069464
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.136592 val_loss=0.063335
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.069558 val_loss=0.051897
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.068743 val_loss=0.050474
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.050845 val_loss=0.024635
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.050093 val_loss=0.024966
Epoch 7/10 - train_loss=0.037715 val_loss=0.051519
Epoch 8/10 - train_loss=0.030092 val_loss=0.034800
Epoch 9/10 - train_loss=0.030517 val_loss=0.036529
Epoch 10/10 - train_loss=0.031082 val_loss=0.035245
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 79.163 Rp/kg
RMSE: 83.371 Rp/kg
MAPE: 2.030 %
sMAPE: 2.053 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:10,953] Trial 16 finished with value: 0.024634786302325736 and parameters: {'hidden_size': 89, 'num_layers': 3, 'dropout': 0.006700877121251336, 'lr': 0.005968508224556961}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.742478 val_loss=0.164832
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.288043 val_loss=0.105106
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.177645 val_loss=0.069527
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.099652 val_loss=0.073760
Epoch 5/10 - train_loss=0.070787 val_loss=0.066023
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.068021 val_loss=0.067816
Epoch 7/10 - train_loss=0.064405 val_loss=0.059326
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.070134 val_loss=0.067566
Epoch 9/10 - train_loss=0.055641 val_loss=0.076282
Epoch 10/10 - train_loss=0.048081 val_loss=0.069866
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 79.891 Rp/kg
RMSE: 81.160 Rp/kg
MAPE: 2.048 %
sMAPE: 2.027 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:11,723] Trial 17 finished with value: 0.05932562202400533 and parameters: {'hidden_size': 110, 'num_layers': 2, 'dropout': 0.2500947940912617, 'lr': 0.0008345796035714942}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.642578 val_loss=0.081529
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.207285 val_loss=0.062671
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.102211 val_loss=0.057810
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.101679 val_loss=0.057399
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.069466 val_loss=0.042196
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.083104 val_loss=0.064049
Epoch 7/10 - train_loss=0.075594 val_loss=0.066036
Epoch 8/10 - train_loss=0.058239 val_loss=0.065048
Epoch 9/10 - train_loss=0.054133 val_loss=0.037136
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.053726 val_loss=0.042374
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 87.343 Rp/kg
RMSE: 89.297 Rp/kg
MAPE: 2.240 %
sMAPE: 2.266 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.548971 val_loss=0.057217
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:12,607] Trial 18 finished with value: 0.037135720591232255 and parameters: {'hidden_size': 63, 'num_layers': 3, 'dropout': 0.13904788780402919, 'lr': 0.0029562865145337978}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.220478 val_loss=0.058108
Epoch 3/10 - train_loss=0.080902 val_loss=0.049483
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.071195 val_loss=0.049720
Epoch 5/10 - train_loss=0.049916 val_loss=0.036542
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.049076 val_loss=0.023674
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.048760 val_loss=0.027871
Epoch 8/10 - train_loss=0.044129 val_loss=0.041690
Epoch 9/10 - train_loss=0.050390 val_loss=0.022500
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.054329 val_loss=0.027409
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 79.139 Rp/kg
RMSE: 80.454 Rp/kg
MAPE: 2.029 %
sMAPE: 2.051 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.740413 val_loss=0.103388
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:13,331] Trial 19 finished with value: 0.02249962084959099 and parameters: {'hidden_size': 89, 'num_layers': 2, 'dropout': 0.3970241814147538, 'lr': 0.007354765000173675}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.332031 val_loss=0.081824
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.214218 val_loss=0.070158
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.107968 val_loss=0.072313
Epoch 5/10 - train_loss=0.074036 val_loss=0.074120
Epoch 6/10 - train_loss=0.107024 val_loss=0.068253
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.084197 val_loss=0.077534
Epoch 8/10 - train_loss=0.079210 val_loss=0.112680
Epoch 9/10 - train_loss=0.064619 val_loss=0.097165
Epoch 10/10 - train_loss=0.050280 val_loss=0.071788
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.1 sec

Final test metrics:
MAE: 112.577 Rp/kg
RMSE: 113.300 Rp/kg
MAPE: 2.887 %
sMAPE: 2.845 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.485120 val_loss=0.069300
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:14,455] Trial 20 finished with value: 0.06825346839776383 and parameters: {'hidden_size': 126, 'num_layers': 3, 'dropout': 0.06828862418578231, 'lr': 0.001014275220138644}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.161580 val_loss=0.054096
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.080457 val_loss=0.037128
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.059093 val_loss=0.039206
Epoch 5/10 - train_loss=0.064394 val_loss=0.034782
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.056270 val_loss=0.031887
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.046557 val_loss=0.028058
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.056060 val_loss=0.028627
Epoch 9/10 - train_loss=0.055920 val_loss=0.029236
Epoch 10/10 - train_loss=0.046224 val_loss=0.025293
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 78.796 Rp/kg
RMSE: 83.656 Rp/kg
MAPE: 2.020 %
sMAPE: 2.044 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:15,395] Trial 21 finished with value: 0.02529288059915995 and parameters: {'hidden_size': 87, 'num_layers': 2, 'dropout': 0.39522617500910545, 'lr': 0.0066611999791530195}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.362250 val_loss=0.062073
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.300355 val_loss=0.045208
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.085174 val_loss=0.045399
Epoch 4/10 - train_loss=0.082889 val_loss=0.040502
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.059727 val_loss=0.036076
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.058242 val_loss=0.038746
Epoch 7/10 - train_loss=0.048933 val_loss=0.031624
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.058353 val_loss=0.036999
Epoch 9/10 - train_loss=0.043802 val_loss=0.032452
Epoch 10/10 - train_loss=0.042968 val_loss=0.024897
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 84.087 Rp/kg
RMSE: 88.385 Rp/kg
MAPE: 2.156 %
sMAPE: 2.182 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.743452 val_loss=0.097064
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:16,242] Trial 22 finished with value: 0.02489683399236395 and parameters: {'hidden_size': 103, 'num_layers': 2, 'dropout': 0.4957729956956702, 'lr': 0.007365207514611018}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.305684 val_loss=0.088703
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.127292 val_loss=0.077981
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.101474 val_loss=0.072341
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.092474 val_loss=0.069034
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.079666 val_loss=0.055741
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.060237 val_loss=0.048861
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.073606 val_loss=0.045098
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.079031 val_loss=0.042925
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.068912 val_loss=0.044792
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 287.525 Rp/kg
RMSE: 287.753 Rp/kg
MAPE: 7.372 %
sMAPE: 7.655 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.583742 val_loss=0.116212
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.283876 val_loss=0.107416
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:17,168] Trial 23 finished with value: 0.042924860890825 and parameters: {'hidden_size': 72, 'num_layers': 3, 'dropout': 0.3644190917739454, 'lr': 0.002620577786097477}. Best is trial 11 with value: 0.019984720645481673.

Epoch 3/10 - train_loss=0.122059 val_loss=0.110650
Epoch 4/10 - train_loss=0.075860 val_loss=0.120117
Epoch 5/10 - train_loss=0.071413 val_loss=0.092713
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.073249 val_loss=0.067465
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.056421 val_loss=0.051884
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.045680 val_loss=0.072940
Epoch 9/10 - train_loss=0.046947 val_loss=0.075283
Epoch 10/10 - train_loss=0.045658 val_loss=0.067262
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 156.122 Rp/kg
RMSE: 156.383 Rp/kg
MAPE: 4.003 %
sMAPE: 3.924 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:18,006] Trial 24 finished with value: 0.051883912835251636 and parameters: {'hidden_size': 93, 'num_layers': 2, 'dropout': 0.2615698968796762, 'lr': 0.004237671186141364}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.452174 val_loss=0.142907
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.101616 val_loss=0.097737
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.082454 val_loss=0.072234
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.067890 val_loss=0.082166
Epoch 5/10 - train_loss=0.056294 val_loss=0.064001
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.050982 val_loss=0.077101
Epoch 7/10 - train_loss=0.046010 val_loss=0.061708
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.052069 val_loss=0.084801
Epoch 9/10 - train_loss=0.048377 val_loss=0.087498
Epoch 10/10 - train_loss=0.043276 val_loss=0.083244
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 208.464 Rp/kg
RMSE: 209.407 Rp/kg
MAPE: 5.345 %
sMAPE: 5.493 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.425168 val_loss=0.061438
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.107548 val_loss=0.065086

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:19,000] Trial 25 finished with value: 0.06170785297357028 and parameters: {'hidden_size': 110, 'num_layers': 3, 'dropout': 0.18890624924455443, 'lr': 0.0079820301028275}. Best is trial 11 with value: 0.019984720645481673.

Epoch 3/10 - train_loss=0.061304 val_loss=0.051094
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.054513 val_loss=0.054668
Epoch 5/10 - train_loss=0.057103 val_loss=0.049727
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.054160 val_loss=0.043429
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.058749 val_loss=0.063865
Epoch 8/10 - train_loss=0.042543 val_loss=0.059759
Epoch 9/10 - train_loss=0.038965 val_loss=0.046608
Epoch 10/10 - train_loss=0.038787 val_loss=0.043189
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 99.817 Rp/kg
RMSE: 100.688 Rp/kg
MAPE: 2.559 %
sMAPE: 2.527 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:19,823] Trial 26 finished with value: 0.043188529367099944 and parameters: {'hidden_size': 71, 'num_layers': 2, 'dropout': 0.16627643413880808, 'lr': 0.00468438223436467}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.476324 val_loss=0.067096
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.207338 val_loss=0.094746
Epoch 3/10 - train_loss=0.097824 val_loss=0.058277
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.066525 val_loss=0.032312
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.060448 val_loss=0.039221
Epoch 6/10 - train_loss=0.060093 val_loss=0.031240
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.056622 val_loss=0.027947
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.044234 val_loss=0.033131
Epoch 9/10 - train_loss=0.031612 val_loss=0.041026
Epoch 10/10 - train_loss=0.038459 val_loss=0.037999
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 269.881 Rp/kg
RMSE: 270.788 Rp/kg
MAPE: 6.920 %
sMAPE: 7.170 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:20,883] Trial 27 finished with value: 0.02794658010871849 and parameters: {'hidden_size': 106, 'num_layers': 3, 'dropout': 0.2895569174609942, 'lr': 0.007168551956969775}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.639924 val_loss=0.078997
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.237064 val_loss=0.070201
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.102029 val_loss=0.047108
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.076576 val_loss=0.050971
Epoch 5/10 - train_loss=0.058519 val_loss=0.040457
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.067785 val_loss=0.039466
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.057091 val_loss=0.037282
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.055414 val_loss=0.034352
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.049598 val_loss=0.031948
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.047720 val_loss=0.035741
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 80.820 Rp/kg
RMSE: 84.888 Rp/kg
MAPE: 2.072 %
sMAPE: 2.096 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:21,888] Trial 28 finished with value: 0.03194775295835359 and parameters: {'hidden_size': 53, 'num_layers': 2, 'dropout': 0.23886552832384475, 'lr': 0.0029618093308603414}. Best is trial 11 with value: 0.019984720645481673.

Device: cuda
Epoch 1/10 - train_loss=0.431271 val_loss=0.109846
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.158174 val_loss=0.098581
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.085452 val_loss=0.142931
Epoch 4/10 - train_loss=0.053646 val_loss=0.091825
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.038717 val_loss=0.082474
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.035022 val_loss=0.078340
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.030804 val_loss=0.061251
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.028986 val_loss=0.053828
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.029603 val_loss=0.044796
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.027491 val_loss=0.043940
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 74.730 Rp/kg
RMSE: 80.828 Rp/kg
MAPE: 1.916 %
sMAPE: 1.938 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.369545 val_loss=0.045145
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.101869 val_loss=0.032514

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:22,650] Trial 29 finished with value: 0.043939585268117524 and parameters: {'hidden_size': 17, 'num_layers': 1, 'dropout': 0.4005450217468052, 'lr': 0.009760198397670956}. Best is trial 11 with value: 0.019984720645481673.

  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.054164 val_loss=0.050555
Epoch 4/10 - train_loss=0.070700 val_loss=0.020833
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.044343 val_loss=0.034048
Epoch 6/10 - train_loss=0.041041 val_loss=0.037530
Epoch 7/10 - train_loss=0.040562 val_loss=0.050675
Epoch 8/10 - train_loss=0.034199 val_loss=0.028325
Epoch 9/10 - train_loss=0.034272 val_loss=0.032779
Epoch 10/10 - train_loss=0.030131 val_loss=0.027577
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 33.874 Rp/kg
RMSE: 35.051 Rp/kg
MAPE: 0.869 %
sMAPE: 0.865 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:23,502] Trial 30 finished with value: 0.02083252937954605 and parameters: {'hidden_size': 117, 'num_layers': 2, 'dropout': 0.04960481126024041, 'lr': 0.005397720799059071}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.390925 val_loss=0.047366
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.113068 val_loss=0.041314
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.058640 val_loss=0.084064
Epoch 4/10 - train_loss=0.052802 val_loss=0.044879
Epoch 5/10 - train_loss=0.046632 val_loss=0.044952
Epoch 6/10 - train_loss=0.041144 val_loss=0.044654
Epoch 7/10 - train_loss=0.043344 val_loss=0.035642
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.041647 val_loss=0.032783
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.034026 val_loss=0.026268
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.028244 val_loss=0.029070
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 30.111 Rp/kg
RMSE: 31.082 Rp/kg
MAPE: 0.772 %
sMAPE: 0.769 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.511540 val_loss=0.079334
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:24,434] Trial 31 finished with value: 0.026267897477836824 and parameters: {'hidden_size': 117, 'num_layers': 2, 'dropout': 0.03896438538799482, 'lr': 0.005649943560501627}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.155121 val_loss=0.055591
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.075619 val_loss=0.061471
Epoch 4/10 - train_loss=0.055614 val_loss=0.047931
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.050648 val_loss=0.059868
Epoch 6/10 - train_loss=0.051580 val_loss=0.037878
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.049659 val_loss=0.037270
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.041878 val_loss=0.034455
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.036650 val_loss=0.041753
Epoch 10/10 - train_loss=0.034693 val_loss=0.042269
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 121.469 Rp/kg
RMSE: 123.540 Rp/kg
MAPE: 3.115 %
sMAPE: 3.065 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:25,234] Trial 32 finished with value: 0.03445516455344003 and parameters: {'hidden_size': 93, 'num_layers': 2, 'dropout': 0.06572450362232823, 'lr': 0.003505863934494507}. Best is trial 11 with value: 0.019984720645481673.

Device: cuda
Epoch 1/10 - train_loss=0.453132 val_loss=0.089460
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.153786 val_loss=0.117420
Epoch 3/10 - train_loss=0.066309 val_loss=0.091771
Epoch 4/10 - train_loss=0.051857 val_loss=0.086158
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.044364 val_loss=0.107160
Epoch 6/10 - train_loss=0.040513 val_loss=0.086256
Epoch 7/10 - train_loss=0.041087 val_loss=0.079944
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.038072 val_loss=0.094577
Epoch 9/10 - train_loss=0.033380 val_loss=0.076748
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.036172 val_loss=0.065994
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 231.216 Rp/kg
RMSE: 231.625 Rp/kg
MAPE: 5.929 %
sMAPE: 5.757 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:26,104] Trial 33 finished with value: 0.06599404325532676 and parameters: {'hidden_size': 81, 'num_layers': 1, 'dropout': 0.2969175804926827, 'lr': 0.004028957237487643}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.470237 val_loss=0.054282
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.130211 val_loss=0.054002
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.054513 val_loss=0.074384
Epoch 4/10 - train_loss=0.072599 val_loss=0.065439
Epoch 5/10 - train_loss=0.109480 val_loss=0.066829
Epoch 6/10 - train_loss=0.078536 val_loss=0.047836
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.051808 val_loss=0.027105
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.038720 val_loss=0.042774
Epoch 9/10 - train_loss=0.039882 val_loss=0.044667
Epoch 10/10 - train_loss=0.041990 val_loss=0.042342
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 47.190 Rp/kg
RMSE: 52.268 Rp/kg
MAPE: 1.210 %
sMAPE: 1.219 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:27,071] Trial 34 finished with value: 0.02710495940212679 and parameters: {'hidden_size': 113, 'num_layers': 2, 'dropout': 0.1057000853159803, 'lr': 0.005760129915644665}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.635916 val_loss=0.412019
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.317167 val_loss=0.064304
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.152952 val_loss=0.055444
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.070261 val_loss=0.054853
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.063882 val_loss=0.052371
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.063959 val_loss=0.060686
Epoch 7/10 - train_loss=0.050272 val_loss=0.036919
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.051525 val_loss=0.031225
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.056369 val_loss=0.030865
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.049769 val_loss=0.039058
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 202.644 Rp/kg
RMSE: 203.421 Rp/kg
MAPE: 5.196 %
sMAPE: 5.336 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.448820 val_loss=0.071687
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:28,117] Trial 35 finished with value: 0.0308645351127309 and parameters: {'hidden_size': 122, 'num_layers': 3, 'dropout': 0.3713465242014571, 'lr': 0.007510395638705501}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.163279 val_loss=0.081480
Epoch 3/10 - train_loss=0.100019 val_loss=0.064147
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.062960 val_loss=0.070290
Epoch 5/10 - train_loss=0.048960 val_loss=0.059570
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.047542 val_loss=0.066190
Epoch 7/10 - train_loss=0.042632 val_loss=0.058481
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.046079 val_loss=0.072716
Epoch 9/10 - train_loss=0.047996 val_loss=0.055948
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.046304 val_loss=0.073860
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 200.000 Rp/kg
RMSE: 200.614 Rp/kg
MAPE: 5.128 %
sMAPE: 4.999 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=1.083470 val_loss=0.480465
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:28,881] Trial 36 finished with value: 0.05594781804737167 and parameters: {'hidden_size': 103, 'num_layers': 1, 'dropout': 0.2314497269201737, 'lr': 0.0020411945593897854}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.975634 val_loss=0.452132
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.844948 val_loss=0.415838
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.683054 val_loss=0.364495
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.474126 val_loss=0.296175
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.360022 val_loss=0.211531
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.306497 val_loss=0.133154
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.262315 val_loss=0.086902
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.233271 val_loss=0.071863
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.205737 val_loss=0.069737
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 15.558 Rp/kg
RMSE: 16.069 Rp/kg
MAPE: 0.399 %
sMAPE: 0.398 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.567138 val_loss=0.138656
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:29,735] Trial 37 finished with value: 0.06973747279673388 and parameters: {'hidden_size': 96, 'num_layers': 2, 'dropout': 0.1547739077623736, 'lr': 0.00010997485811271344}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.219244 val_loss=0.088251
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.115807 val_loss=0.117017
Epoch 4/10 - train_loss=0.081446 val_loss=0.060306
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.073266 val_loss=0.097928
Epoch 6/10 - train_loss=0.054433 val_loss=0.093471
Epoch 7/10 - train_loss=0.045193 val_loss=0.096394
Epoch 8/10 - train_loss=0.046335 val_loss=0.072570
Epoch 9/10 - train_loss=0.045781 val_loss=0.091913
Epoch 10/10 - train_loss=0.037716 val_loss=0.064071
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 126.955 Rp/kg
RMSE: 127.220 Rp/kg
MAPE: 3.255 %
sMAPE: 3.309 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:30,632] Trial 38 finished with value: 0.060306266469148856 and parameters: {'hidden_size': 75, 'num_layers': 3, 'dropout': 0.11453280388492192, 'lr': 0.0037004922350967542}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.681371 val_loss=0.109320
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.265831 val_loss=0.088039
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.125362 val_loss=0.068203
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.095541 val_loss=0.078049
Epoch 5/10 - train_loss=0.060969 val_loss=0.074528
Epoch 6/10 - train_loss=0.054678 val_loss=0.071152
Epoch 7/10 - train_loss=0.048059 val_loss=0.080933
Epoch 8/10 - train_loss=0.053268 val_loss=0.067901
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.045758 val_loss=0.077574
Epoch 10/10 - train_loss=0.042543 val_loss=0.079064
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 211.863 Rp/kg
RMSE: 212.454 Rp/kg
MAPE: 5.432 %
sMAPE: 5.288 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.296268 val_loss=0.077803
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.066719 val_loss=0.078003

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:31,493] Trial 39 finished with value: 0.06790149853152422 and parameters: {'hidden_size': 82, 'num_layers': 2, 'dropout': 0.041033578106100976, 'lr': 0.0015208629459744015}. Best is trial 11 with value: 0.019984720645481673.

Epoch 3/10 - train_loss=0.049650 val_loss=0.056979
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.042399 val_loss=0.049696
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.040094 val_loss=0.043136
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.035930 val_loss=0.040034
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.033753 val_loss=0.048422
Epoch 8/10 - train_loss=0.031005 val_loss=0.046276
Epoch 9/10 - train_loss=0.035580 val_loss=0.043100
Epoch 10/10 - train_loss=0.032298 val_loss=0.044382
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.7 sec

Final test metrics:
MAE: 200.515 Rp/kg
RMSE: 201.265 Rp/kg
MAPE: 5.141 %
sMAPE: 5.012 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:32,225] Trial 40 finished with value: 0.040033518749089975 and parameters: {'hidden_size': 123, 'num_layers': 1, 'dropout': 0.3423690175586851, 'lr': 0.005177960059690431}. Best is trial 11 with value: 0.019984720645481673.

Epoch 1/10 - train_loss=0.683767 val_loss=0.094424
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.311135 val_loss=0.049225
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.140853 val_loss=0.055879
Epoch 4/10 - train_loss=0.066551 val_loss=0.037330
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.047328 val_loss=0.052879
Epoch 6/10 - train_loss=0.040769 val_loss=0.043513
Epoch 7/10 - train_loss=0.037529 val_loss=0.044059
Epoch 8/10 - train_loss=0.031248 val_loss=0.030682
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.032508 val_loss=0.034498
Epoch 10/10 - train_loss=0.026905 val_loss=0.031883
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 61.308 Rp/kg
RMSE: 63.152 Rp/kg
MAPE: 1.572 %
sMAPE: 1.585 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.482515 val_loss=0.071902
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:33,191] Trial 41 finished with value: 0.030682324564468986 and parameters: {'hidden_size': 89, 'num_layers': 3, 'dropout': 0.006260666368234323, 'lr': 0.006118096265312985}. Best is trial 11 with value: 0.019984720645481673.

Epoch 2/10 - train_loss=0.177258 val_loss=0.043383
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.077703 val_loss=0.057242
Epoch 4/10 - train_loss=0.076523 val_loss=0.042241
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.055766 val_loss=0.042316
Epoch 6/10 - train_loss=0.041012 val_loss=0.025500
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.032928 val_loss=0.020419
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.030097 val_loss=0.031173
Epoch 9/10 - train_loss=0.032481 val_loss=0.017802
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.031102 val_loss=0.017009
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:34,109] Trial 42 finished with value: 0.01700913294482587 and parameters: {'hidden_size': 88, 'num_layers': 3, 'dropout': 0.004761280203738366, 'lr': 0.008412246286759703}. Best is trial 42 with value: 0.01700913294482587.

Training finished in 0.9 sec

Final test metrics:
MAE: 149.632 Rp/kg
RMSE: 156.722 Rp/kg
MAPE: 3.837 %
sMAPE: 3.919 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.500561 val_loss=0.096447
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.141405 val_loss=0.074481
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.058741 val_loss=0.074365
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.049800 val_loss=0.052971
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.049361 val_loss=0.054077
Epoch 6/10 - train_loss=0.049804 val_loss=0.052745
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 7/10 - train_loss=0.040358 val_loss=0.060794
Epoch 8/10 - train_loss=0.035120 val_loss=0.036496
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.030277 val_loss=0.031546
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.034522 val_loss=0.035164
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 88.718 Rp/kg
RMSE: 89.970 Rp/kg
MAPE: 2.275 %
sMAPE: 2.302 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:34,974] Trial 43 finished with value: 0.03154554214347061 and parameters: {'hidden_size': 86, 'num_layers': 3, 'dropout': 0.044503535765188396, 'lr': 0.008050949319533816}. Best is trial 42 with value: 0.01700913294482587.

Epoch 1/10 - train_loss=0.567141 val_loss=0.146935
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.263996 val_loss=0.045321
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.068632 val_loss=0.080000
Epoch 4/10 - train_loss=0.071938 val_loss=0.031251
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.054960 val_loss=0.027842
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.043730 val_loss=0.029117
Epoch 7/10 - train_loss=0.043159 val_loss=0.020046
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.033412 val_loss=0.023231
Epoch 9/10 - train_loss=0.029066 val_loss=0.020277
Epoch 10/10 - train_loss=0.030979 val_loss=0.018003
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 170.299 Rp/kg
RMSE: 173.513 Rp/kg
MAPE: 4.367 %
sMAPE: 4.468 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.659679 val_loss=0.103397
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:35,892] Trial 44 finished with value: 0.01800342879040324 and parameters: {'hidden_size': 100, 'num_layers': 3, 'dropout': 0.07604013237443623, 'lr': 0.008814218476558932}. Best is trial 42 with value: 0.01700913294482587.

Epoch 2/10 - train_loss=0.319839 val_loss=0.092152
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.129302 val_loss=0.051742
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.079724 val_loss=0.029750
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.055018 val_loss=0.036154
Epoch 6/10 - train_loss=0.039172 val_loss=0.048489
Epoch 7/10 - train_loss=0.052055 val_loss=0.036034
Epoch 8/10 - train_loss=0.043842 val_loss=0.031368
Epoch 9/10 - train_loss=0.038148 val_loss=0.026377
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.031072 val_loss=0.027513
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 242.030 Rp/kg
RMSE: 242.347 Rp/kg
MAPE: 6.206 %
sMAPE: 6.405 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:36,985] Trial 45 finished with value: 0.02637651217962379 and parameters: {'hidden_size': 100, 'num_layers': 3, 'dropout': 0.0790770372107012, 'lr': 0.008188225493272337}. Best is trial 42 with value: 0.01700913294482587.

Device: cuda
Epoch 1/10 - train_loss=0.444143 val_loss=0.166402
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.180233 val_loss=0.173098
Epoch 3/10 - train_loss=0.065983 val_loss=0.110551
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.060982 val_loss=0.105815
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.063557 val_loss=0.073492
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.043391 val_loss=0.099941
Epoch 7/10 - train_loss=0.049424 val_loss=0.126135
Epoch 8/10 - train_loss=0.059641 val_loss=0.087421
Epoch 9/10 - train_loss=0.054691 val_loss=0.093298
Epoch 10/10 - train_loss=0.033566 val_loss=0.112116
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 191.543 Rp/kg
RMSE: 193.283 Rp/kg
MAPE: 4.911 %
sMAPE: 5.037 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:37,849] Trial 46 finished with value: 0.07349157053513906 and parameters: {'hidden_size': 108, 'num_layers': 3, 'dropout': 0.08952837453904833, 'lr': 0.009621209953520553}. Best is trial 42 with value: 0.01700913294482587.

Epoch 1/10 - train_loss=0.548064 val_loss=0.062130
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.127101 val_loss=0.065559
Epoch 3/10 - train_loss=0.081802 val_loss=0.053057
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.058823 val_loss=0.060827
Epoch 5/10 - train_loss=0.054545 val_loss=0.056033
Epoch 6/10 - train_loss=0.053736 val_loss=0.080485
Epoch 7/10 - train_loss=0.034596 val_loss=0.047559
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.034364 val_loss=0.056816
Epoch 9/10 - train_loss=0.035994 val_loss=0.046201
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.028743 val_loss=0.050474
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 67.207 Rp/kg
RMSE: 70.176 Rp/kg
MAPE: 1.723 %
sMAPE: 1.707 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.517244 val_loss=0.069899
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.150185 val_loss=0.052670
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:38,871] Trial 47 finished with value: 0.0462013709483974 and parameters: {'hidden_size': 113, 'num_layers': 3, 'dropout': 0.026202390276743343, 'lr': 0.004812833685828612}. Best is trial 42 with value: 0.01700913294482587.

Epoch 3/10 - train_loss=0.076815 val_loss=0.051358
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/10 - train_loss=0.063050 val_loss=0.041073
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 5/10 - train_loss=0.063813 val_loss=0.046078
Epoch 6/10 - train_loss=0.058748 val_loss=0.046839
Epoch 7/10 - train_loss=0.047023 val_loss=0.055836
Epoch 8/10 - train_loss=0.042595 val_loss=0.040736
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/10 - train_loss=0.045088 val_loss=0.040161
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 10/10 - train_loss=0.039145 val_loss=0.053051
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.8 sec

Final test metrics:
MAE: 36.426 Rp/kg
RMSE: 44.768 Rp/kg
MAPE: 0.934 %
sMAPE: 0.928 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:39,720] Trial 48 finished with value: 0.04016083911923108 and parameters: {'hidden_size': 117, 'num_layers': 3, 'dropout': 0.1739729902123249, 'lr': 0.003211695132547743}. Best is trial 42 with value: 0.01700913294482587.

Epoch 1/10 - train_loss=0.621386 val_loss=0.072991
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 2/10 - train_loss=0.217727 val_loss=0.057206
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/10 - train_loss=0.118449 val_loss=0.074663
Epoch 4/10 - train_loss=0.090123 val_loss=0.092854
Epoch 5/10 - train_loss=0.059851 val_loss=0.053885
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/10 - train_loss=0.053226 val_loss=0.075899
Epoch 7/10 - train_loss=0.054413 val_loss=0.044721
  Saved best model to models/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 8/10 - train_loss=0.051229 val_loss=0.064876
Epoch 9/10 - train_loss=0.044827 val_loss=0.051725
Epoch 10/10 - train_loss=0.047729 val_loss=0.079805
Loading best checkpoint from models/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 0.9 sec

Final test metrics:
MAE: 101.037 Rp/kg
RMSE: 102.792 Rp/kg
MAPE: 2.591 %
sMAPE: 2.556 %
Directional Accuracy: 0.00 %
Best trial params: {'hidden_size': 88, 'num_layers': 3, 'dropout': 0.004761280203738366, 'lr': 0.008412246286759703}
Retraining full model with best params...
Device: cuda
Epoch 1/60 - train_loss=0.551206 val_loss=0.132645
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:40,655] Trial 49 finished with value: 0.04472142878678901 and parameters: {'hidden_size': 94, 'num_layers': 3, 'dropout': 0.12563480636986551, 'lr': 0.002448599479781284}. Best is trial 42 with value: 0.01700913294482587.

Epoch 2/60 - train_loss=0.191596 val_loss=0.038509
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 3/60 - train_loss=0.049626 val_loss=0.036184
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 4/60 - train_loss=0.041852 val_loss=0.063064
Epoch 5/60 - train_loss=0.036931 val_loss=0.026094
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 6/60 - train_loss=0.046117 val_loss=0.044532
Epoch 7/60 - train_loss=0.036472 val_loss=0.048487
Epoch 8/60 - train_loss=0.030819 val_loss=0.021318
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 9/60 - train_loss=0.030425 val_loss=0.034348
Epoch 10/60 - train_loss=0.032957 val_loss=0.013578
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth
Epoch 11/60 - train_loss=0.026460 val_loss=0.022475
Epoch 12/60 - train_loss=0.043217 val_loss=0.016896
Epoch 13/60 - train_loss=0.041710 val_loss=0.019117
Epoch 14/60 - train_loss=0.032907 val_loss=0.022589
Epoch 15/60 - train_loss=0.029857 val_loss=0.015489
Epoch 16/60 - train_loss=0.034201 val_loss=0.026068
Epoch 17/60 - train_loss=0.028235 val_loss=0.014934
Epoch 18/60 - train_loss=0.026442 val_loss=0.023631
Epoch 19/60 - train_loss=0.029233 val_loss=0.018799
Epoch 20/60 - train_loss=0.028266 val_loss=0.015777
Early stopping after 20 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Jagung_Pipil_Kering/lstm_Jagung_Pipil_Kering_multivariate.pth for final evaluation
Training finished in 1.7 sec

Final test metrics:
MAE: 105.714 Rp/kg
RMSE: 113.739 Rp/kg
MAPE: 2.711 %
sMAPE: 2.754 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

--- Running Optuna for Beras Premium ---

2026-06-02 17:27:44.238834: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-02 17:27:44.256888: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-02 17:27:44.281558: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-02 17:27:44.288694: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-02 17:27:44.306835: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2026-06-02 17:27:47,270] A new study created in memory with name: no-name-fdb5cd8c-74e0-4b3f-9fca-0016c2cdb834

Device: cuda
Epoch 1/10 - train_loss=0.305386 val_loss=1.078898
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.035827 val_loss=0.210707
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.008966 val_loss=0.247721
Epoch 4/10 - train_loss=0.006015 val_loss=0.210390
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.005117 val_loss=0.228060
Epoch 6/10 - train_loss=0.004961 val_loss=0.212645
Epoch 7/10 - train_loss=0.004616 val_loss=0.216186
Epoch 8/10 - train_loss=0.004386 val_loss=0.218882
Epoch 9/10 - train_loss=0.004396 val_loss=0.208564
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.004127 val_loss=0.219124
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.6 sec

Final test metrics:
MAE: 455.988 Rp/kg
RMSE: 456.006 Rp/kg
MAPE: 3.508 %
sMAPE: 3.447 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:49,879] Trial 0 finished with value: 0.20856356107956403 and parameters: {'hidden_size': 21, 'num_layers': 2, 'dropout': 0.21443604365171465, 'lr': 0.0027993795135781625}. Best is trial 0 with value: 0.20856356107956403.

Epoch 1/10 - train_loss=0.254025 val_loss=0.967074
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.027447 val_loss=0.184032
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.008657 val_loss=0.282457
Epoch 4/10 - train_loss=0.006171 val_loss=0.219033
Epoch 5/10 - train_loss=0.005416 val_loss=0.218737
Epoch 6/10 - train_loss=0.005029 val_loss=0.202138
Epoch 7/10 - train_loss=0.004649 val_loss=0.195652
Epoch 8/10 - train_loss=0.004393 val_loss=0.182732
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.004222 val_loss=0.185311
Epoch 10/10 - train_loss=0.004021 val_loss=0.182745
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.2 sec

Final test metrics:
MAE: 390.013 Rp/kg
RMSE: 390.155 Rp/kg
MAPE: 3.000 %
sMAPE: 2.956 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.398884 val_loss=1.303658
  Saved best model to models/lstm_Beras_Premium_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:51,083] Trial 1 finished with value: 0.1827315746189712 and parameters: {'hidden_size': 95, 'num_layers': 1, 'dropout': 0.12740026710801083, 'lr': 0.00043686499996118305}. Best is trial 1 with value: 0.1827315746189712.

Epoch 2/10 - train_loss=0.047611 val_loss=0.147953
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.009107 val_loss=0.204586
Epoch 4/10 - train_loss=0.006347 val_loss=0.155544
Epoch 5/10 - train_loss=0.005459 val_loss=0.168041
Epoch 6/10 - train_loss=0.005404 val_loss=0.158371
Epoch 7/10 - train_loss=0.005041 val_loss=0.161571
Epoch 8/10 - train_loss=0.004923 val_loss=0.159871
Epoch 9/10 - train_loss=0.004808 val_loss=0.157246
Epoch 10/10 - train_loss=0.004737 val_loss=0.163312
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.3 sec

Final test metrics:
MAE: 909.106 Rp/kg
RMSE: 909.107 Rp/kg
MAPE: 6.993 %
sMAPE: 6.757 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.233685 val_loss=0.205024
  Saved best model to models/lstm_Beras_Premium_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:52,461] Trial 2 finished with value: 0.14795326199624445 and parameters: {'hidden_size': 86, 'num_layers': 2, 'dropout': 0.32870645776449453, 'lr': 0.0005373179781262168}. Best is trial 2 with value: 0.14795326199624445.

Epoch 2/10 - train_loss=0.016993 val_loss=0.181734
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.006128 val_loss=0.172286
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.005174 val_loss=0.168153
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.004298 val_loss=0.163732
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.004305 val_loss=0.154121
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.004203 val_loss=0.158418
Epoch 8/10 - train_loss=0.003762 val_loss=0.157709
Epoch 9/10 - train_loss=0.003781 val_loss=0.160698
Epoch 10/10 - train_loss=0.003562 val_loss=0.163583
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.2 sec

Final test metrics:
MAE: 474.463 Rp/kg
RMSE: 474.482 Rp/kg
MAPE: 3.650 %
sMAPE: 3.584 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.485089 val_loss=2.693286
  Saved best model to models/lstm_Beras_Premium_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:53,658] Trial 3 finished with value: 0.15412113467207203 and parameters: {'hidden_size': 89, 'num_layers': 2, 'dropout': 0.02548447148533184, 'lr': 0.000985398709391992}. Best is trial 2 with value: 0.14795326199624445.

Epoch 2/10 - train_loss=0.197531 val_loss=0.872688
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.023374 val_loss=0.191671
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.008991 val_loss=0.183965
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.006981 val_loss=0.173164
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.006444 val_loss=0.170200
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.005678 val_loss=0.171914
Epoch 8/10 - train_loss=0.005672 val_loss=0.168812
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.005411 val_loss=0.176254
Epoch 10/10 - train_loss=0.005351 val_loss=0.166159
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.3 sec

Final test metrics:
MAE: 494.396 Rp/kg
RMSE: 494.399 Rp/kg
MAPE: 3.803 %
sMAPE: 3.732 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.594623 val_loss=2.979758
  Saved best model to models/lstm_Beras_Premium_multivariate.pth

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:55,020] Trial 4 finished with value: 0.16615909400891948 and parameters: {'hidden_size': 122, 'num_layers': 3, 'dropout': 0.18612704106433559, 'lr': 0.0002078361821158502}. Best is trial 2 with value: 0.14795326199624445.

Epoch 2/10 - train_loss=0.458467 val_loss=2.571438
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.337916 val_loss=2.163548
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.231946 val_loss=1.730412
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.144089 val_loss=1.348975
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.081714 val_loss=1.021519
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.044642 val_loss=0.779319
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.026160 val_loss=0.590478
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.016429 val_loss=0.475001
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.011731 val_loss=0.404180
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.0 sec

Final test metrics:
MAE: 197.289 Rp/kg
RMSE: 197.345 Rp/kg
MAPE: 1.518 %
sMAPE: 1.506 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:56,054] Trial 5 finished with value: 0.40418011871735 and parameters: {'hidden_size': 24, 'num_layers': 1, 'dropout': 0.07454938000181932, 'lr': 0.00030313904663103076}. Best is trial 2 with value: 0.14795326199624445.

Epoch 1/10 - train_loss=0.342604 val_loss=0.922630
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.032212 val_loss=0.161124
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.009332 val_loss=0.191159
Epoch 4/10 - train_loss=0.006481 val_loss=0.163685
Epoch 5/10 - train_loss=0.005652 val_loss=0.166640
Epoch 6/10 - train_loss=0.005117 val_loss=0.171819
Epoch 7/10 - train_loss=0.005159 val_loss=0.164811
Epoch 8/10 - train_loss=0.005119 val_loss=0.174617
Epoch 9/10 - train_loss=0.004948 val_loss=0.169724
Epoch 10/10 - train_loss=0.004631 val_loss=0.170219
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.1 sec

Final test metrics:
MAE: 720.607 Rp/kg
RMSE: 720.637 Rp/kg
MAPE: 5.543 %
sMAPE: 5.394 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:57,236] Trial 6 finished with value: 0.16112364306078328 and parameters: {'hidden_size': 53, 'num_layers': 2, 'dropout': 0.2754857321298907, 'lr': 0.0008582789466127392}. Best is trial 2 with value: 0.14795326199624445.

Device: cuda
Epoch 1/10 - train_loss=0.183206 val_loss=0.183868
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.011268 val_loss=0.184928
Epoch 3/10 - train_loss=0.005876 val_loss=0.154424
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.006612 val_loss=0.211831
Epoch 5/10 - train_loss=0.004282 val_loss=0.162868
Epoch 6/10 - train_loss=0.003459 val_loss=0.172989
Epoch 7/10 - train_loss=0.005252 val_loss=0.161185
Epoch 8/10 - train_loss=0.004389 val_loss=0.202870
Epoch 9/10 - train_loss=0.004379 val_loss=0.158823
Epoch 10/10 - train_loss=0.003137 val_loss=0.174159
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.7 sec

Final test metrics:
MAE: 515.097 Rp/kg
RMSE: 515.142 Rp/kg
MAPE: 3.962 %
sMAPE: 3.885 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:27:58,969] Trial 7 finished with value: 0.15442352190420225 and parameters: {'hidden_size': 100, 'num_layers': 3, 'dropout': 0.350060149601701, 'lr': 0.0051146976963361125}. Best is trial 2 with value: 0.14795326199624445.

Epoch 1/10 - train_loss=0.648574 val_loss=2.345960
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.493041 val_loss=2.292069
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.226549 val_loss=1.686798
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.101127 val_loss=0.814517
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.024095 val_loss=0.212015
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.010216 val_loss=0.188158
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.007231 val_loss=0.202247
Epoch 8/10 - train_loss=0.006748 val_loss=0.195263
Epoch 9/10 - train_loss=0.006500 val_loss=0.189545
Epoch 10/10 - train_loss=0.006030 val_loss=0.195394
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.6 sec

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:00,601] Trial 8 finished with value: 0.18815756473061326 and parameters: {'hidden_size': 63, 'num_layers': 3, 'dropout': 0.1652910630762366, 'lr': 0.00018129041794293576}. Best is trial 2 with value: 0.14795326199624445.

Final test metrics:
MAE: 505.949 Rp/kg
RMSE: 505.952 Rp/kg
MAPE: 3.892 %
sMAPE: 3.818 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.154359 val_loss=0.157593
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.010850 val_loss=0.176332
Epoch 3/10 - train_loss=0.006016 val_loss=0.172334
Epoch 4/10 - train_loss=0.004880 val_loss=0.172445
Epoch 5/10 - train_loss=0.004280 val_loss=0.167007
Epoch 6/10 - train_loss=0.004560 val_loss=0.172956
Epoch 7/10 - train_loss=0.003526 val_loss=0.171076
Epoch 8/10 - train_loss=0.003453 val_loss=0.160319
Epoch 9/10 - train_loss=0.003206 val_loss=0.162592
Epoch 10/10 - train_loss=0.003415 val_loss=0.171859
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.7 sec

Final test metrics:
MAE: 534.599 Rp/kg
RMSE: 534.640 Rp/kg
MAPE: 4.112 %
sMAPE: 4.029 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:02,348] Trial 9 finished with value: 0.15759327465837653 and parameters: {'hidden_size': 29, 'num_layers': 2, 'dropout': 0.45171080093345234, 'lr': 0.009718723430533253}. Best is trial 2 with value: 0.14795326199624445.

Device: cuda
Epoch 1/10 - train_loss=0.545177 val_loss=2.281934
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.424568 val_loss=1.974035
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.322140 val_loss=1.680247
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.232797 val_loss=1.379575
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.156583 val_loss=1.092479
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.093338 val_loss=0.835368
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.047218 val_loss=0.611784
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.021851 val_loss=0.449647
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.012156 val_loss=0.357120
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.009430 val_loss=0.320036
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.7 sec

Final test metrics:
MAE: 424.100 Rp/kg
RMSE: 424.140 Rp/kg
MAPE: 3.262 %
sMAPE: 3.210 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:04,083] Trial 10 finished with value: 0.3200361065856822 and parameters: {'hidden_size': 59, 'num_layers': 1, 'dropout': 0.4935915000865391, 'lr': 0.00011777616847712353}. Best is trial 2 with value: 0.14795326199624445.

Epoch 1/10 - train_loss=0.253947 val_loss=0.163118
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.018399 val_loss=0.202520
Epoch 3/10 - train_loss=0.006663 val_loss=0.178807
Epoch 4/10 - train_loss=0.004907 val_loss=0.172801
Epoch 5/10 - train_loss=0.004418 val_loss=0.161383
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.004219 val_loss=0.156054
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.005006 val_loss=0.154449
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.004224 val_loss=0.176757
Epoch 9/10 - train_loss=0.003723 val_loss=0.168462
Epoch 10/10 - train_loss=0.003595 val_loss=0.154901
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.9 sec

Final test metrics:
MAE: 442.289 Rp/kg
RMSE: 442.514 Rp/kg
MAPE: 3.402 %
sMAPE: 3.345 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:06,040] Trial 11 finished with value: 0.15444873152421668 and parameters: {'hidden_size': 81, 'num_layers': 2, 'dropout': 0.0032002998920766246, 'lr': 0.0009671234274384355}. Best is trial 2 with value: 0.14795326199624445.

Epoch 1/10 - train_loss=0.161231 val_loss=0.282381
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.012871 val_loss=0.144404
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.006419 val_loss=0.151113
Epoch 4/10 - train_loss=0.004957 val_loss=0.149997
Epoch 5/10 - train_loss=0.004747 val_loss=0.148142
Epoch 6/10 - train_loss=0.004891 val_loss=0.152103
Epoch 7/10 - train_loss=0.004581 val_loss=0.158282
Epoch 8/10 - train_loss=0.004071 val_loss=0.147765
Epoch 9/10 - train_loss=0.004471 val_loss=0.145858
Epoch 10/10 - train_loss=0.003876 val_loss=0.146675
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.9 sec

Final test metrics:
MAE: 451.900 Rp/kg
RMSE: 451.953 Rp/kg
MAPE: 3.476 %
sMAPE: 3.417 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:08,014] Trial 12 finished with value: 0.14440397913386296 and parameters: {'hidden_size': 116, 'num_layers': 2, 'dropout': 0.3714543362890065, 'lr': 0.0012615121103887266}. Best is trial 12 with value: 0.14440397913386296.

Device: cuda
Epoch 1/10 - train_loss=0.099851 val_loss=0.162031
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.008904 val_loss=0.141404
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.005533 val_loss=0.145783
Epoch 4/10 - train_loss=0.004514 val_loss=0.144979
Epoch 5/10 - train_loss=0.004041 val_loss=0.165691
Epoch 6/10 - train_loss=0.004358 val_loss=0.153780
Epoch 7/10 - train_loss=0.005137 val_loss=0.140853
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.003941 val_loss=0.148002
Epoch 9/10 - train_loss=0.003678 val_loss=0.147326
Epoch 10/10 - train_loss=0.003022 val_loss=0.138685
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.9 sec

Final test metrics:
MAE: 515.664 Rp/kg
RMSE: 515.873 Rp/kg
MAPE: 3.967 %
sMAPE: 3.889 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:09,954] Trial 13 finished with value: 0.13868450712073932 and parameters: {'hidden_size': 126, 'num_layers': 2, 'dropout': 0.36795476257675536, 'lr': 0.0021802752144438517}. Best is trial 13 with value: 0.13868450712073932.

Epoch 1/10 - train_loss=0.128857 val_loss=0.216934
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.014194 val_loss=0.190991
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.006180 val_loss=0.163344
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.005831 val_loss=0.149469
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.005433 val_loss=0.146868
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.004527 val_loss=0.144661
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.004293 val_loss=0.151376
Epoch 8/10 - train_loss=0.004025 val_loss=0.152225
Epoch 9/10 - train_loss=0.004025 val_loss=0.143255
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.003789 val_loss=0.142341
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:12,048] Trial 14 finished with value: 0.14234059371731497 and parameters: {'hidden_size': 127, 'num_layers': 2, 'dropout': 0.4009299118337203, 'lr': 0.0019756358623519783}. Best is trial 13 with value: 0.13868450712073932.

Training finished in 2.0 sec

Final test metrics:
MAE: 407.118 Rp/kg
RMSE: 407.321 Rp/kg
MAPE: 3.132 %
sMAPE: 3.083 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.104229 val_loss=0.234308
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007130 val_loss=0.179200
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004603 val_loss=0.172577
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003786 val_loss=0.162617
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003364 val_loss=0.152571
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003251 val_loss=0.145778
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.003001 val_loss=0.142450
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.003004 val_loss=0.143000
Epoch 9/10 - train_loss=0.002691 val_loss=0.151878
Epoch 10/10 - train_loss=0.002503 val_loss=0.146131
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in -1.0 sec

Final test metrics:
MAE: 381.941 Rp/kg
RMSE: 382.435 Rp/kg
MAPE: 2.938 %
sMAPE: 2.895 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:11,112] Trial 15 finished with value: 0.14245032161087184 and parameters: {'hidden_size': 126, 'num_layers': 1, 'dropout': 0.4215681239089691, 'lr': 0.002263753124785897}. Best is trial 13 with value: 0.13868450712073932.

Device: cuda
Epoch 1/10 - train_loss=0.121647 val_loss=0.176859
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.010007 val_loss=0.182130
Epoch 3/10 - train_loss=0.006396 val_loss=0.178039
Epoch 4/10 - train_loss=0.005056 val_loss=0.179742
Epoch 5/10 - train_loss=0.004218 val_loss=0.182302
Epoch 6/10 - train_loss=0.003960 val_loss=0.169325
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.004203 val_loss=0.169118
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.003370 val_loss=0.162541
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.003052 val_loss=0.167715
Epoch 10/10 - train_loss=0.002687 val_loss=0.165826
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.4 sec

Final test metrics:
MAE: 465.933 Rp/kg
RMSE: 466.020 Rp/kg
MAPE: 3.584 %
sMAPE: 3.521 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:13,549] Trial 16 finished with value: 0.16254136140470382 and parameters: {'hidden_size': 111, 'num_layers': 3, 'dropout': 0.27561337551861, 'lr': 0.0028542223557970984}. Best is trial 13 with value: 0.13868450712073932.

Epoch 1/10 - train_loss=0.158851 val_loss=0.251110
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.011379 val_loss=0.160320
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.005750 val_loss=0.151736
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.005177 val_loss=0.158067
Epoch 5/10 - train_loss=0.004662 val_loss=0.159313
Epoch 6/10 - train_loss=0.004231 val_loss=0.155206
Epoch 7/10 - train_loss=0.004011 val_loss=0.157882
Epoch 8/10 - train_loss=0.004101 val_loss=0.149301
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.004147 val_loss=0.146103
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.004012 val_loss=0.151966
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.0 sec

Final test metrics:
MAE: 469.298 Rp/kg
RMSE: 469.494 Rp/kg
MAPE: 3.610 %
sMAPE: 3.546 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:15,573] Trial 17 finished with value: 0.14610288500205262 and parameters: {'hidden_size': 105, 'num_layers': 2, 'dropout': 0.4091392591464092, 'lr': 0.001794152399417976}. Best is trial 13 with value: 0.13868450712073932.

Epoch 1/10 - train_loss=0.230177 val_loss=0.230071
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.012424 val_loss=0.169273
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.005552 val_loss=0.166239
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.005067 val_loss=0.174272
Epoch 5/10 - train_loss=0.003928 val_loss=0.161266
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003363 val_loss=0.175169
Epoch 7/10 - train_loss=0.003425 val_loss=0.182135
Epoch 8/10 - train_loss=0.003818 val_loss=0.171997
Epoch 9/10 - train_loss=0.003896 val_loss=0.194617
Epoch 10/10 - train_loss=0.003258 val_loss=0.164241
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:17,641] Trial 18 finished with value: 0.16126606013480718 and parameters: {'hidden_size': 125, 'num_layers': 3, 'dropout': 0.2946107776211561, 'lr': 0.005344211668273265}. Best is trial 13 with value: 0.13868450712073932.

Training finished in 2.0 sec

Final test metrics:
MAE: 486.319 Rp/kg
RMSE: 486.359 Rp/kg
MAPE: 3.741 %
sMAPE: 3.672 %
Directional Accuracy: 0.00 %
Device: cuda
Epoch 1/10 - train_loss=0.093718 val_loss=0.127887
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007041 val_loss=0.125155
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003896 val_loss=0.120387
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003589 val_loss=0.116193
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003246 val_loss=0.110140
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003122 val_loss=0.143466
Epoch 7/10 - train_loss=0.002735 val_loss=0.117635
Epoch 8/10 - train_loss=0.002958 val_loss=0.121244
Epoch 9/10 - train_loss=0.002317 val_loss=0.124405
Epoch 10/10 - train_loss=0.002308 val_loss=0.137623
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 1.9 sec

Final test metrics:
MAE: 402.458 Rp/kg
RMSE: 402.938 Rp/kg
MAPE: 3.096 %
sMAPE: 3.049 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:19,659] Trial 19 finished with value: 0.1101403705678977 and parameters: {'hidden_size': 114, 'num_layers': 1, 'dropout': 0.3875134306378784, 'lr': 0.004436304622739796}. Best is trial 19 with value: 0.1101403705678977.

Epoch 1/10 - train_loss=0.047191 val_loss=0.114795
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.005312 val_loss=0.130764
Epoch 3/10 - train_loss=0.003579 val_loss=0.118236
Epoch 4/10 - train_loss=0.003019 val_loss=0.111714
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002945 val_loss=0.116616
Epoch 6/10 - train_loss=0.002469 val_loss=0.121566
Epoch 7/10 - train_loss=0.002465 val_loss=0.120665
Epoch 8/10 - train_loss=0.002440 val_loss=0.113877
Epoch 9/10 - train_loss=0.002179 val_loss=0.118582
Epoch 10/10 - train_loss=0.002169 val_loss=0.105848
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.6 sec

Final test metrics:
MAE: 368.724 Rp/kg
RMSE: 369.394 Rp/kg
MAPE: 2.836 %
sMAPE: 2.797 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:22,324] Trial 20 finished with value: 0.10584807192737405 and parameters: {'hidden_size': 77, 'num_layers': 1, 'dropout': 0.48425072003179737, 'lr': 0.0066193097727252894}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.072464 val_loss=0.219627
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006492 val_loss=0.167751
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003865 val_loss=0.173362
Epoch 4/10 - train_loss=0.004057 val_loss=0.158310
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.004194 val_loss=0.141934
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003201 val_loss=0.147758
Epoch 7/10 - train_loss=0.002968 val_loss=0.145691
Epoch 8/10 - train_loss=0.002500 val_loss=0.149028
Epoch 9/10 - train_loss=0.002226 val_loss=0.148638
Epoch 10/10 - train_loss=0.002119 val_loss=0.145221
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.2 sec

Final test metrics:
MAE: 440.704 Rp/kg
RMSE: 441.736 Rp/kg
MAPE: 3.390 %
sMAPE: 3.333 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:24,632] Trial 21 finished with value: 0.1419337684070909 and parameters: {'hidden_size': 69, 'num_layers': 1, 'dropout': 0.48772751067236014, 'lr': 0.005212340426852674}. Best is trial 20 with value: 0.10584807192737405.

Device: cuda
Epoch 1/10 - train_loss=0.066792 val_loss=0.211950
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006611 val_loss=0.178541
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004342 val_loss=0.181280
Epoch 4/10 - train_loss=0.003377 val_loss=0.170361
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003092 val_loss=0.143059
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.002579 val_loss=0.152996
Epoch 7/10 - train_loss=0.002190 val_loss=0.167271
Epoch 8/10 - train_loss=0.003501 val_loss=0.147861
Epoch 9/10 - train_loss=0.002212 val_loss=0.150041
Epoch 10/10 - train_loss=0.001887 val_loss=0.158141
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.5 sec

Final test metrics:
MAE: 530.351 Rp/kg
RMSE: 530.438 Rp/kg
MAPE: 4.080 %
sMAPE: 3.998 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:27,168] Trial 22 finished with value: 0.14305922389030457 and parameters: {'hidden_size': 43, 'num_layers': 1, 'dropout': 0.45569399838398683, 'lr': 0.009197416701360702}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.070124 val_loss=0.194910
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.005825 val_loss=0.151405
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003738 val_loss=0.140950
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003215 val_loss=0.135677
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003345 val_loss=0.161885
Epoch 6/10 - train_loss=0.003087 val_loss=0.123694
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.002591 val_loss=0.147938
Epoch 8/10 - train_loss=0.002422 val_loss=0.129670
Epoch 9/10 - train_loss=0.002393 val_loss=0.178415
Epoch 10/10 - train_loss=0.002396 val_loss=0.185113
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.4 sec

Final test metrics:
MAE: 425.543 Rp/kg
RMSE: 426.172 Rp/kg
MAPE: 3.273 %
sMAPE: 3.221 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:29,646] Trial 23 finished with value: 0.12369353532210572 and parameters: {'hidden_size': 78, 'num_layers': 1, 'dropout': 0.37225150575598964, 'lr': 0.003631146908801832}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.137688 val_loss=0.221754
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.008218 val_loss=0.164776
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004542 val_loss=0.157578
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003755 val_loss=0.151607
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003182 val_loss=0.164660
Epoch 6/10 - train_loss=0.003420 val_loss=0.162928
Epoch 7/10 - train_loss=0.003001 val_loss=0.144275
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.002968 val_loss=0.144748
Epoch 9/10 - train_loss=0.002469 val_loss=0.142108
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.002975 val_loss=0.164241
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.6 sec

Final test metrics:
MAE: 399.781 Rp/kg
RMSE: 400.357 Rp/kg
MAPE: 3.075 %
sMAPE: 3.029 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:32,352] Trial 24 finished with value: 0.14210756287559287 and parameters: {'hidden_size': 79, 'num_layers': 1, 'dropout': 0.44235539091310866, 'lr': 0.0038731512802141423}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.067924 val_loss=0.144850
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006319 val_loss=0.149454
Epoch 3/10 - train_loss=0.003917 val_loss=0.145333
Epoch 4/10 - train_loss=0.003314 val_loss=0.131926
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002655 val_loss=0.140850
Epoch 6/10 - train_loss=0.002568 val_loss=0.150120
Epoch 7/10 - train_loss=0.002403 val_loss=0.166144
Epoch 8/10 - train_loss=0.002461 val_loss=0.164063
Epoch 9/10 - train_loss=0.002334 val_loss=0.152551
Epoch 10/10 - train_loss=0.002187 val_loss=0.177531
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.8 sec

Final test metrics:
MAE: 450.230 Rp/kg
RMSE: 450.297 Rp/kg
MAPE: 3.463 %
sMAPE: 3.404 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:35,275] Trial 25 finished with value: 0.13192642378536137 and parameters: {'hidden_size': 73, 'num_layers': 1, 'dropout': 0.39356376587585473, 'lr': 0.0069408563246461516}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.170953 val_loss=0.152565
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.012558 val_loss=0.220892
Epoch 3/10 - train_loss=0.004632 val_loss=0.179739
Epoch 4/10 - train_loss=0.003718 val_loss=0.179517
Epoch 5/10 - train_loss=0.003121 val_loss=0.177849
Epoch 6/10 - train_loss=0.002853 val_loss=0.178191
Epoch 7/10 - train_loss=0.002768 val_loss=0.178347
Epoch 8/10 - train_loss=0.002566 val_loss=0.175319
Epoch 9/10 - train_loss=0.002445 val_loss=0.171629
Epoch 10/10 - train_loss=0.002608 val_loss=0.178398
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 1056.999 Rp/kg
RMSE: 1057.067 Rp/kg
MAPE: 8.131 %
sMAPE: 7.813 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:38,610] Trial 26 finished with value: 0.15256516267726947 and parameters: {'hidden_size': 38, 'num_layers': 1, 'dropout': 0.33431632075499035, 'lr': 0.003866247225415371}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.089231 val_loss=0.172703
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007221 val_loss=0.150227
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003918 val_loss=0.149981
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003425 val_loss=0.148681
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003316 val_loss=0.131971
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003016 val_loss=0.138474
Epoch 7/10 - train_loss=0.002762 val_loss=0.149218
Epoch 8/10 - train_loss=0.002682 val_loss=0.140213
Epoch 9/10 - train_loss=0.002615 val_loss=0.150119
Epoch 10/10 - train_loss=0.002414 val_loss=0.149894
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 452.252 Rp/kg
RMSE: 452.595 Rp/kg
MAPE: 3.479 %
sMAPE: 3.419 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:41,997] Trial 27 finished with value: 0.13197130845351654 and parameters: {'hidden_size': 95, 'num_layers': 1, 'dropout': 0.3119971669784588, 'lr': 0.0035889723484357127}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.094959 val_loss=0.188995
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007940 val_loss=0.170791
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004160 val_loss=0.177444
Epoch 4/10 - train_loss=0.003222 val_loss=0.172870
Epoch 5/10 - train_loss=0.002891 val_loss=0.185114
Epoch 6/10 - train_loss=0.002776 val_loss=0.159381
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.002486 val_loss=0.160089
Epoch 8/10 - train_loss=0.002544 val_loss=0.162405
Epoch 9/10 - train_loss=0.002252 val_loss=0.168309
Epoch 10/10 - train_loss=0.002248 val_loss=0.185923
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 0.0 sec

Final test metrics:
MAE: 526.868 Rp/kg
RMSE: 526.959 Rp/kg
MAPE: 4.053 %
sMAPE: 3.972 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:42,130] Trial 28 finished with value: 0.1593814722032516 and parameters: {'hidden_size': 52, 'num_layers': 1, 'dropout': 0.49982333610638313, 'lr': 0.007008603705109651}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.087296 val_loss=0.296821
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.009284 val_loss=0.138152
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004992 val_loss=0.154405
Epoch 4/10 - train_loss=0.003715 val_loss=0.158509
Epoch 5/10 - train_loss=0.003721 val_loss=0.154571
Epoch 6/10 - train_loss=0.003364 val_loss=0.148674
Epoch 7/10 - train_loss=0.003338 val_loss=0.148083
Epoch 8/10 - train_loss=0.002712 val_loss=0.146947
Epoch 9/10 - train_loss=0.002659 val_loss=0.141932
Epoch 10/10 - train_loss=0.002802 val_loss=0.153678
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.8 sec

Final test metrics:
MAE: 592.702 Rp/kg
RMSE: 592.742 Rp/kg
MAPE: 4.559 %
sMAPE: 4.458 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:45,038] Trial 29 finished with value: 0.13815208195478884 and parameters: {'hidden_size': 71, 'num_layers': 1, 'dropout': 0.23404568008314258, 'lr': 0.0030132233668249426}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.124131 val_loss=0.174103
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.010199 val_loss=0.160554
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.005258 val_loss=0.154124
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.004323 val_loss=0.145647
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.004263 val_loss=0.140795
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003776 val_loss=0.141055
Epoch 7/10 - train_loss=0.003493 val_loss=0.159899
Epoch 8/10 - train_loss=0.003654 val_loss=0.165389
Epoch 9/10 - train_loss=0.003258 val_loss=0.156009
Epoch 10/10 - train_loss=0.003138 val_loss=0.158019
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 393.270 Rp/kg
RMSE: 393.565 Rp/kg
MAPE: 3.025 %
sMAPE: 2.980 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:48,386] Trial 30 finished with value: 0.14079502191055904 and parameters: {'hidden_size': 109, 'num_layers': 1, 'dropout': 0.4503196033397384, 'lr': 0.0013545302113463097}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.066992 val_loss=0.145080
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006052 val_loss=0.158782
Epoch 3/10 - train_loss=0.003792 val_loss=0.154983
Epoch 4/10 - train_loss=0.002984 val_loss=0.157616
Epoch 5/10 - train_loss=0.002559 val_loss=0.159761
Epoch 6/10 - train_loss=0.002889 val_loss=0.159146
Epoch 7/10 - train_loss=0.002500 val_loss=0.165287
Epoch 8/10 - train_loss=0.002299 val_loss=0.154657
Epoch 9/10 - train_loss=0.002079 val_loss=0.156963
Epoch 10/10 - train_loss=0.002588 val_loss=0.174051
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 607.448 Rp/kg
RMSE: 607.488 Rp/kg
MAPE: 4.673 %
sMAPE: 4.566 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:51,683] Trial 31 finished with value: 0.14508013978794024 and parameters: {'hidden_size': 74, 'num_layers': 1, 'dropout': 0.38255013587070263, 'lr': 0.006735534483036739}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.063015 val_loss=0.146326
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006369 val_loss=0.135701
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003508 val_loss=0.129419
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003238 val_loss=0.118535
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003139 val_loss=0.135087
Epoch 6/10 - train_loss=0.002655 val_loss=0.126127
Epoch 7/10 - train_loss=0.002487 val_loss=0.122943
Epoch 8/10 - train_loss=0.002108 val_loss=0.120144
Epoch 9/10 - train_loss=0.002074 val_loss=0.146348
Epoch 10/10 - train_loss=0.002042 val_loss=0.137739
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.1 sec

Final test metrics:
MAE: 386.441 Rp/kg
RMSE: 386.827 Rp/kg
MAPE: 2.973 %
sMAPE: 2.929 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:54,906] Trial 32 finished with value: 0.118534517655899 and parameters: {'hidden_size': 91, 'num_layers': 1, 'dropout': 0.414583764884159, 'lr': 0.007019291505061848}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.077317 val_loss=0.213636
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006046 val_loss=0.163157
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.003925 val_loss=0.146629
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003894 val_loss=0.146453
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003376 val_loss=0.136860
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.002906 val_loss=0.148640
Epoch 7/10 - train_loss=0.002757 val_loss=0.141996
Epoch 8/10 - train_loss=0.003099 val_loss=0.165944
Epoch 9/10 - train_loss=0.002913 val_loss=0.153025
Epoch 10/10 - train_loss=0.002218 val_loss=0.151760
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 437.342 Rp/kg
RMSE: 437.622 Rp/kg
MAPE: 3.364 %
sMAPE: 3.308 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:28:58,180] Trial 33 finished with value: 0.13686000405774487 and parameters: {'hidden_size': 91, 'num_layers': 1, 'dropout': 0.41818670111938294, 'lr': 0.004525141723498275}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.067345 val_loss=0.110821
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007365 val_loss=0.114945
Epoch 3/10 - train_loss=0.004570 val_loss=0.188537
Epoch 4/10 - train_loss=0.003305 val_loss=0.136620
Epoch 5/10 - train_loss=0.002404 val_loss=0.144958
Epoch 6/10 - train_loss=0.002673 val_loss=0.133011
Epoch 7/10 - train_loss=0.002223 val_loss=0.136630
Epoch 8/10 - train_loss=0.002036 val_loss=0.142067
Epoch 9/10 - train_loss=0.002368 val_loss=0.127427
Epoch 10/10 - train_loss=0.002375 val_loss=0.138233
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.2 sec

Final test metrics:
MAE: 252.573 Rp/kg
RMSE: 256.360 Rp/kg
MAPE: 1.943 %
sMAPE: 1.924 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:01,436] Trial 34 finished with value: 0.11082132245329293 and parameters: {'hidden_size': 84, 'num_layers': 1, 'dropout': 0.3591976012028498, 'lr': 0.007462365604851617}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.074271 val_loss=0.142701
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006829 val_loss=0.152172
Epoch 3/10 - train_loss=0.004199 val_loss=0.162407
Epoch 4/10 - train_loss=0.003129 val_loss=0.153787
Epoch 5/10 - train_loss=0.002911 val_loss=0.161212
Epoch 6/10 - train_loss=0.002633 val_loss=0.150886
Epoch 7/10 - train_loss=0.003000 val_loss=0.167476
Epoch 8/10 - train_loss=0.002471 val_loss=0.153147
Epoch 9/10 - train_loss=0.002324 val_loss=0.154823
Epoch 10/10 - train_loss=0.002175 val_loss=0.160579
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.5 sec

Final test metrics:
MAE: 756.120 Rp/kg
RMSE: 757.161 Rp/kg
MAPE: 5.816 %
sMAPE: 5.652 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:04,997] Trial 35 finished with value: 0.14270087670196185 and parameters: {'hidden_size': 86, 'num_layers': 1, 'dropout': 0.4661333352529027, 'lr': 0.007290497301438531}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.065929 val_loss=0.158684
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006170 val_loss=0.163944
Epoch 3/10 - train_loss=0.003662 val_loss=0.162489
Epoch 4/10 - train_loss=0.003018 val_loss=0.142017
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002704 val_loss=0.164009
Epoch 6/10 - train_loss=0.002453 val_loss=0.148489
Epoch 7/10 - train_loss=0.002737 val_loss=0.161350
Epoch 8/10 - train_loss=0.002451 val_loss=0.163295
Epoch 9/10 - train_loss=0.002190 val_loss=0.134383
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.002430 val_loss=0.136572
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.1 sec

Final test metrics:
MAE: 456.546 Rp/kg
RMSE: 457.034 Rp/kg
MAPE: 3.512 %
sMAPE: 3.451 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:08,330] Trial 36 finished with value: 0.13438281358836532 and parameters: {'hidden_size': 95, 'num_layers': 1, 'dropout': 0.346232937775617, 'lr': 0.008514450322296188}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.084454 val_loss=0.177032
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007439 val_loss=0.131716
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004307 val_loss=0.141117
Epoch 4/10 - train_loss=0.003447 val_loss=0.131091
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002847 val_loss=0.134985
Epoch 6/10 - train_loss=0.002791 val_loss=0.147276
Epoch 7/10 - train_loss=0.002417 val_loss=0.132407
Epoch 8/10 - train_loss=0.002274 val_loss=0.149503
Epoch 9/10 - train_loss=0.002194 val_loss=0.161003
Epoch 10/10 - train_loss=0.002167 val_loss=0.137951
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.5 sec

Final test metrics:
MAE: 360.932 Rp/kg
RMSE: 361.377 Rp/kg
MAPE: 2.776 %
sMAPE: 2.738 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:10,872] Trial 37 finished with value: 0.13109074605556278 and parameters: {'hidden_size': 103, 'num_layers': 1, 'dropout': 0.2349607698358647, 'lr': 0.0058826733178366985}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.071800 val_loss=0.167857
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007204 val_loss=0.199589
Epoch 3/10 - train_loss=0.004296 val_loss=0.168912
Epoch 4/10 - train_loss=0.002760 val_loss=0.164339
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002513 val_loss=0.146599
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.002658 val_loss=0.155340
Epoch 7/10 - train_loss=0.002199 val_loss=0.153300
Epoch 8/10 - train_loss=0.001995 val_loss=0.152993
Epoch 9/10 - train_loss=0.001895 val_loss=0.151212
Epoch 10/10 - train_loss=0.001950 val_loss=0.171927
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in -0.5 sec

Final test metrics:
MAE: 430.809 Rp/kg
RMSE: 431.119 Rp/kg
MAPE: 3.314 %
sMAPE: 3.260 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:10,399] Trial 38 finished with value: 0.14659860870474345 and parameters: {'hidden_size': 86, 'num_layers': 1, 'dropout': 0.4340228136989237, 'lr': 0.009975435087872875}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.067098 val_loss=0.138979
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006338 val_loss=0.170021
Epoch 3/10 - train_loss=0.004138 val_loss=0.136442
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003262 val_loss=0.124522
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003170 val_loss=0.129159
Epoch 6/10 - train_loss=0.002659 val_loss=0.136684
Epoch 7/10 - train_loss=0.002746 val_loss=0.175201
Epoch 8/10 - train_loss=0.002890 val_loss=0.144046
Epoch 9/10 - train_loss=0.002636 val_loss=0.166514
Epoch 10/10 - train_loss=0.002602 val_loss=0.146632
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.3 sec

Final test metrics:
MAE: 328.817 Rp/kg
RMSE: 329.513 Rp/kg
MAPE: 2.529 %
sMAPE: 2.498 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:12,827] Trial 39 finished with value: 0.12452151215115151 and parameters: {'hidden_size': 117, 'num_layers': 1, 'dropout': 0.4681238883921494, 'lr': 0.004466641810547959}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.374194 val_loss=1.596864
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.070169 val_loss=0.426409
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.010830 val_loss=0.277827
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.006648 val_loss=0.323858
Epoch 5/10 - train_loss=0.005666 val_loss=0.274121
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.005336 val_loss=0.271869
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.004926 val_loss=0.264289
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.004805 val_loss=0.241887
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.004628 val_loss=0.251143
Epoch 10/10 - train_loss=0.004364 val_loss=0.230186
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.3 sec

Final test metrics:
MAE: 401.223 Rp/kg
RMSE: 401.256 Rp/kg
MAPE: 3.086 %
sMAPE: 3.039 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:15,208] Trial 40 finished with value: 0.23018628213699763 and parameters: {'hidden_size': 65, 'num_layers': 1, 'dropout': 0.317856318434295, 'lr': 0.0005467925093101249}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.092781 val_loss=0.307151
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.009617 val_loss=0.206040
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004853 val_loss=0.177589
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003828 val_loss=0.159003
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003486 val_loss=0.148309
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003007 val_loss=0.144387
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.003717 val_loss=0.144181
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.003371 val_loss=0.183290
Epoch 9/10 - train_loss=0.002742 val_loss=0.162456
Epoch 10/10 - train_loss=0.002775 val_loss=0.148854
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.3 sec

Final test metrics:
MAE: 360.885 Rp/kg
RMSE: 361.692 Rp/kg
MAPE: 2.776 %
sMAPE: 2.738 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:17,585] Trial 41 finished with value: 0.14418086433758984 and parameters: {'hidden_size': 81, 'num_layers': 1, 'dropout': 0.3689452737137101, 'lr': 0.003154791724957003}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.056194 val_loss=0.135701
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.005755 val_loss=0.155142
Epoch 3/10 - train_loss=0.004038 val_loss=0.157989
Epoch 4/10 - train_loss=0.003801 val_loss=0.131256
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003317 val_loss=0.130069
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.002766 val_loss=0.136247
Epoch 7/10 - train_loss=0.002580 val_loss=0.141474
Epoch 8/10 - train_loss=0.002349 val_loss=0.144697
Epoch 9/10 - train_loss=0.002328 val_loss=0.137359
Epoch 10/10 - train_loss=0.002231 val_loss=0.142560
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.1 sec

Final test metrics:
MAE: 411.125 Rp/kg
RMSE: 412.420 Rp/kg
MAPE: 3.162 %
sMAPE: 3.113 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:19,768] Trial 42 finished with value: 0.1300689924459953 and parameters: {'hidden_size': 79, 'num_layers': 1, 'dropout': 0.3600145536125417, 'lr': 0.00586750844118015}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.077487 val_loss=0.123270
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006732 val_loss=0.152371
Epoch 3/10 - train_loss=0.004332 val_loss=0.148199
Epoch 4/10 - train_loss=0.003478 val_loss=0.155422
Epoch 5/10 - train_loss=0.003522 val_loss=0.135622
Epoch 6/10 - train_loss=0.003337 val_loss=0.160052
Epoch 7/10 - train_loss=0.002987 val_loss=0.160043
Epoch 8/10 - train_loss=0.003033 val_loss=0.148781
Epoch 9/10 - train_loss=0.002718 val_loss=0.149640
Epoch 10/10 - train_loss=0.002512 val_loss=0.155841
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.0 sec

Final test metrics:
MAE: 620.876 Rp/kg
RMSE: 621.361 Rp/kg
MAPE: 4.776 %
sMAPE: 4.664 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:21,849] Trial 43 finished with value: 0.12327021737764408 and parameters: {'hidden_size': 99, 'num_layers': 1, 'dropout': 0.08389595039922165, 'lr': 0.004347169370742582}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.080351 val_loss=0.168583
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006223 val_loss=0.180320
Epoch 3/10 - train_loss=0.003892 val_loss=0.160763
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003457 val_loss=0.170866
Epoch 5/10 - train_loss=0.004257 val_loss=0.181293
Epoch 6/10 - train_loss=0.003509 val_loss=0.171640
Epoch 7/10 - train_loss=0.002872 val_loss=0.149454
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.002910 val_loss=0.136749
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.002398 val_loss=0.146707
Epoch 10/10 - train_loss=0.002324 val_loss=0.161880
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.1 sec

Final test metrics:
MAE: 493.312 Rp/kg
RMSE: 494.222 Rp/kg
MAPE: 3.795 %
sMAPE: 3.724 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:23,968] Trial 44 finished with value: 0.13674935084078219 and parameters: {'hidden_size': 99, 'num_layers': 1, 'dropout': 0.15181068236226747, 'lr': 0.004596386502753796}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.073284 val_loss=0.156811
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.006429 val_loss=0.161509
Epoch 3/10 - train_loss=0.003974 val_loss=0.149500
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.002952 val_loss=0.139927
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.002883 val_loss=0.149718
Epoch 6/10 - train_loss=0.003023 val_loss=0.148008
Epoch 7/10 - train_loss=0.002591 val_loss=0.136792
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.002584 val_loss=0.143060
Epoch 9/10 - train_loss=0.002093 val_loss=0.162477
Epoch 10/10 - train_loss=0.002030 val_loss=0.155561
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.2 sec

Final test metrics:
MAE: 461.507 Rp/kg
RMSE: 461.948 Rp/kg
MAPE: 3.550 %
sMAPE: 3.488 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:26,221] Trial 45 finished with value: 0.13679241640614226 and parameters: {'hidden_size': 92, 'num_layers': 1, 'dropout': 0.09085880653276951, 'lr': 0.008163829850910144}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.102132 val_loss=0.195067
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.008590 val_loss=0.129184
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004558 val_loss=0.147276
Epoch 4/10 - train_loss=0.003966 val_loss=0.130263
Epoch 5/10 - train_loss=0.003604 val_loss=0.132518
Epoch 6/10 - train_loss=0.003413 val_loss=0.130711
Epoch 7/10 - train_loss=0.003290 val_loss=0.136810
Epoch 8/10 - train_loss=0.003006 val_loss=0.128776
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.003006 val_loss=0.116114
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.003888 val_loss=0.120511
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.0 sec

Final test metrics:
MAE: 410.855 Rp/kg
RMSE: 411.187 Rp/kg
MAPE: 3.160 %
sMAPE: 3.111 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:28,254] Trial 46 finished with value: 0.11611380481294223 and parameters: {'hidden_size': 117, 'num_layers': 1, 'dropout': 0.08371902990173075, 'lr': 0.002388371314320851}. Best is trial 20 with value: 0.10584807192737405.

Device: cuda
Epoch 1/10 - train_loss=0.104187 val_loss=0.316460
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.009251 val_loss=0.175441
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004635 val_loss=0.145959
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003941 val_loss=0.140388
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003567 val_loss=0.144571
Epoch 6/10 - train_loss=0.003262 val_loss=0.143333
Epoch 7/10 - train_loss=0.003239 val_loss=0.133052
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.002960 val_loss=0.123859
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.002774 val_loss=0.115828
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.002817 val_loss=0.126298
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.0 sec

Final test metrics:
MAE: 460.515 Rp/kg
RMSE: 460.802 Rp/kg
MAPE: 3.542 %
sMAPE: 3.481 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:30,367] Trial 47 finished with value: 0.11582779971423088 and parameters: {'hidden_size': 115, 'num_layers': 1, 'dropout': 0.10956533795631128, 'lr': 0.002560647953236156}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.098004 val_loss=0.278042
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.007683 val_loss=0.158839
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.004299 val_loss=0.137870
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003503 val_loss=0.132026
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003254 val_loss=0.126300
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 6/10 - train_loss=0.003078 val_loss=0.125367
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 7/10 - train_loss=0.003019 val_loss=0.124976
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.002757 val_loss=0.119969
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 9/10 - train_loss=0.002508 val_loss=0.129256
Epoch 10/10 - train_loss=0.002600 val_loss=0.121935
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.0 sec

Final test metrics:
MAE: 382.873 Rp/kg
RMSE: 383.845 Rp/kg
MAPE: 2.945 %
sMAPE: 2.902 %
Directional Accuracy: 0.00 %
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:32,474] Trial 48 finished with value: 0.11996878695662146 and parameters: {'hidden_size': 116, 'num_layers': 1, 'dropout': 0.11589386933811777, 'lr': 0.0024881773688615735}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/10 - train_loss=0.125673 val_loss=0.158493
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 2/10 - train_loss=0.010114 val_loss=0.124593
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 3/10 - train_loss=0.005056 val_loss=0.122832
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 4/10 - train_loss=0.003796 val_loss=0.119424
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 5/10 - train_loss=0.003595 val_loss=0.120403
Epoch 6/10 - train_loss=0.003279 val_loss=0.124075
Epoch 7/10 - train_loss=0.003045 val_loss=0.117436
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 8/10 - train_loss=0.003223 val_loss=0.128746
Epoch 9/10 - train_loss=0.002778 val_loss=0.110275
  Saved best model to models/lstm_Beras_Premium_multivariate.pth
Epoch 10/10 - train_loss=0.003036 val_loss=0.111739
Loading best checkpoint from models/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 2.3 sec

Final test metrics:
MAE: 413.542 Rp/kg
RMSE: 413.973 Rp/kg
MAPE: 3.181 %
sMAPE: 3.131 %
Directional Accuracy: 0.00 %
Best trial params: {'hidden_size': 77, 'num_layers': 1, 'dropout': 0.48425072003179737, 'lr': 0.0066193097727252894}
Retraining full model with best params...
Device: cuda

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
[I 2026-06-02 17:29:34,875] Trial 49 finished with value: 0.11027466307406301 and parameters: {'hidden_size': 118, 'num_layers': 2, 'dropout': 0.03873903698581016, 'lr': 0.0026133657136091777}. Best is trial 20 with value: 0.10584807192737405.

Epoch 1/60 - train_loss=0.064884 val_loss=0.162301
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 2/60 - train_loss=0.007414 val_loss=0.154441
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 3/60 - train_loss=0.004193 val_loss=0.151934
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 4/60 - train_loss=0.003374 val_loss=0.163729
Epoch 5/60 - train_loss=0.003178 val_loss=0.145627
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 6/60 - train_loss=0.002497 val_loss=0.145014
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 7/60 - train_loss=0.002456 val_loss=0.160656
Epoch 8/60 - train_loss=0.002343 val_loss=0.137015
  Saved best model to /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth
Epoch 9/60 - train_loss=0.002278 val_loss=0.142606
Epoch 10/60 - train_loss=0.002217 val_loss=0.150660
Epoch 11/60 - train_loss=0.002217 val_loss=0.163186
Epoch 12/60 - train_loss=0.002595 val_loss=0.150565
Epoch 13/60 - train_loss=0.001882 val_loss=0.156456
Epoch 14/60 - train_loss=0.001820 val_loss=0.156812
Epoch 15/60 - train_loss=0.001672 val_loss=0.155669
Epoch 16/60 - train_loss=0.001501 val_loss=0.142089
Epoch 17/60 - train_loss=0.001857 val_loss=0.151516
Epoch 18/60 - train_loss=0.001394 val_loss=0.150215
Early stopping after 18 epochs with no improvement for 10 epochs.
Loading best checkpoint from /home/rna_13/DataScienceProject/dsproject_agriculturepredict/runs/optuna/Beras_Premium/lstm_Beras_Premium_multivariate.pth for final evaluation
Training finished in 3.5 sec

Final test metrics:
MAE: 445.723 Rp/kg
RMSE: 446.020 Rp/kg
MAPE: 3.429 %
sMAPE: 3.371 %
Directional Accuracy: 0.00 %

/home/rna_13/DataScienceProject/dsproject_agriculturepredict/src/train.py:260: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
/home/rna_13/anaconda3/envs/rapids-24.10/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

### Insight Ringkas dari Hasil Optuna

- **Ringkasan umum:** Optuna sudah menjalankan retrain multivariate untuk semua komoditas. Saya membandingkan metrik multivariate Optuna (`runs/all_commodity_optuna_summary.csv`) dengan baseline multivariate saat ini (`runs/recomputed_compare.csv`) dan menyimpan ringkasan di `runs/optuna_vs_baseline_summary.csv`.
- **Hasil per komoditas (MAE baseline → MAE Optuna):**
    - Beras Premium: 465.15 → 288.05 (peningkatan besar; gunakan model Optuna sebagai kandidat utama)
    - Jagung Pipil Kering: 117.20 → 78.81 (peningkatan jelas; layak dipakai)
    - Kacang Hijau: 3.38 → 3.19 (peningkatan kecil; stabil)
    - Beras Medium: 64.40 → 132.45 (Optuna MUNTAH; hasil Optuna lebih buruk — investigasi diperlukan)
- **Rekomendasi tindakan singkat:**
    1. Teruskan dan gunakan model Optuna untuk `Beras Premium` dan `Jagung Pipil Kering` (evaluasi kembali pada holdout/horizon operasional sebelum deployment).
    2. Untuk `Beras Medium`, cek data input untuk Optuna retrain (scaling, join eksogen, horizon), dan ulangi Optuna dengan batasan/hyperprior yang lebih konservatif atau kurangi search space.
    3. `Kacang Hijau` menunjukkan sedikit perbaikan — pertimbangkan run Optuna tambahan dengan fokus pada stability/regularization jika biaya compute kecil.
    4. Simpan model terbaik Optuna + checkpoint dan tambahkan kolom per-commodity `optuna_source` pada katalog eksperimen untuk traceability.

Jika mau, saya bisa: memeriksa `runs/optuna_metrics.csv` untuk melihat hyperparameter terpilih, menyusun per-commodity plot per-trial, atau menyiapkan skrip untuk mempromosikan model Optuna terpilih ke folder `models/optuna/`.